#!bin/bash

# Strings are passed to the scrieta but this is redundant!  noCHF

# python ../ssdilep/scripts/merge.py --var="invMass_4" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="0" --input="/afs/f9.ijs.si/home/miham/Diboson36_12" --output="./diboson" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="invMassOS1" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="0" --input="/afs/f9.ijs.si/home/miham/Diboson36_12" --output="./diboson" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="invMassOS2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="0" --input="/afs/f9.ijs.si/home/miham/Diboson36_12" --output="./diboson" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="ZbosonPt_2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="0" --input="/afs/f9.ijs.si/home/miham/Diboson36_12" --output="./diboson" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="ZbosonEta_2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="0" --input="/afs/f9.ijs.si/home/miham/Diboson36_12" --output="./diboson" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="nelectrons" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="0" --input="/afs/f9.ijs.si/home/miham/Diboson36_12" --output="./diboson" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="njets" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="0" --input="/afs/f9.ijs.si/home/miham/Diboson36_12" --output="./diboson" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="nbjets" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="0" --input="/afs/f9.ijs.si/home/miham/Diboson36_12" --output="./diboson" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="NPV" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="0" --input="/afs/f9.ijs.si/home/miham/Diboson36_12" --output="./diboson" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="met_trk_et" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="0" --input="/afs/f9.ijs.si/home/miham/Diboson36_12" --output="./diboson" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="met_clus_et" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="0" --input="/afs/f9.ijs.si/home/miham/Diboson36_12" --output="./diboson" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_pt_2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="0" --input="/afs/f9.ijs.si/home/miham/Diboson36_12" --output="./diboson" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_pt_2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="0" --input="/afs/f9.ijs.si/home/miham/Diboson36_12" --output="./diboson" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_eta_2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="0" --input="/afs/f9.ijs.si/home/miham/Diboson36_12" --output="./diboson" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_eta_2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="0" --input="/afs/f9.ijs.si/home/miham/Diboson36_12" --output="./diboson" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_phi_2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="0" --input="/afs/f9.ijs.si/home/miham/Diboson36_12" --output="./diboson" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_phi_2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="0" --input="/afs/f9.ijs.si/home/miham/Diboson36_12" --output="./diboson" --makeplot=True --fakest="FakeFactorGeneral"