# # # #!bin/bash

# # # ##OSCR
# python ../ssdilep/scripts/merge.py -E True --var="invMass" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}#e^{#mp})" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="HT" --xlabel="#Sigma p_{T} [GeV]"        --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonPt" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonEta" --xlabel="#eta(e^{#pm}e^{#pm})" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="nelectrons" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="NPV" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="met_trk_et" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_lead_pt" --xlabel="p_{T}(lead e)" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_sublead_pt" --xlabel="p_{T}(sublead e)" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_lead_eta" --xlabel="#eta(lead e)" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_sublead_eta" --xlabel="#eta(sublead e)" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_lead_phi" --xlabel="#phi(lead e)" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_sublead_phi" --xlabel="#phi(sublead e)" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # # ##OSCR b veto
# # python ../ssdilep/scripts/merge.py -E True --var="invMass" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="DR" --xlabel="#DeltaR(e^{#pm}e^{#mp})" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonPt" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonEta" --xlabel="#eta(e^{#pm}e^{#pm})" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="nelectrons" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="NPV" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="met_trk_et" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_pt" --xlabel="p_{T}(lead e)" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_pt" --xlabel="p_{T}(sublead e)" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_eta" --xlabel="#eta(lead e)" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_eta" --xlabel="#eta(sublead e)" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_phi" --xlabel="#phi(lead e)" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_phi" --xlabel="#phi(sublead e)" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # ##SSVR
# # python ../ssdilep/scripts/merge.py -E True --var="invMass_2" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}#e^{#pm})" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --var="HT"  --xlabel="#Sigma p_{T} [GeV]"       --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonPt_2" --xlabel="p_{T}(e^{#pm}e^{#pm})" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}e^{#pm})" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="nelectrons" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="nsspairs" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="NPV" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="met_trk_et" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead e)" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead e)" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_lead_eta_2" --xlabel="#eta(lead e)" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead e)" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_lead_phi_2" --xlabel="#phi(lead e)" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead e)" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # # ##ttbar OSCR
# # python ../ssdilep/scripts/merge.py -E True --var="invMass" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="DR4" --xlabel="#DeltaR(e^{#pm}e^{#mp})" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonPt" --xlabel="p_{T}(e^{#pm}e^{#pm})" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonEta" --xlabel="#eta(e^{#pm}e^{#pm})" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="nelectrons" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="NPV" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="met_trk_et" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_pt" --xlabel="p_{T}(lead e)" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_pt" --xlabel="p_{T}(sublead e)" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_eta" --xlabel="#eta(lead e)" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_eta" --xlabel="#eta(sublead e)" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_phi" --xlabel="#phi(lead e)" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_phi" --xlabel="#phi(sublead e)" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # ##ttbar SSVR
# # python ../ssdilep/scripts/merge.py -E True --var="invMass_3" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="DR4" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonPt_2" --xlabel="p_{T}(e^{#pm}e^{#pm})" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}e^{#pm})" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="nelectrons" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="NPV" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="met_trk_et" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead e)" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead e)" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_eta_2" --xlabel="#eta(lead e)" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead e)" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_phi_2" --xlabel="#phi(lead e)" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead e)" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # ##diboson
# # python ../ssdilep/scripts/merge.py -E True --var="invMass_4" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}#e^{#pm})" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --var="HT2" --xlabel="#Sigma p_{T} [GeV]"        --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="invMassOS1" --xlabel="m(e^{#pm}e^{#mp}) [GeV]"  --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="invMassOS2" --xlabel="m(e^{#pm}e^{#mp}) [GeV]"  --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonPt_2" --xlabel="p_{T}(e^{#pm}e^{#pm})" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}e^{#pm})" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="nelectrons" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # # python ../ssdilep/scripts/merge.py -E True --var="njets" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # # python ../ssdilep/scripts/merge.py -E True --var="nbjets" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # # python ../ssdilep/scripts/merge.py -E True --var="NPV" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="met_trk_et" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead e)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead e)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_third_pt_2" --xlabel="p_{T}(third e)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_lead_eta_2" --xlabel="#eta(lead e)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead e)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_third_eta_2" --xlabel="#eta(third e)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_lead_phi_2" --xlabel="#phi(lead e)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead e)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_third_phi_2" --xlabel="#phi(third e)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # # ##three electron
# # python ../ssdilep/scripts/merge.py -E True --var="invMass_4" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}#e^{#pm})" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --var="HT"  --xlabel="#Sigma p_{T} [GeV]"       --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="invMassOS1" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="invMassOS2" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonPt_2" --xlabel="p_{T}(e^{#pm}e^{#pm})" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}e^{#pm})" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="nelectrons" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # # python ../ssdilep/scripts/merge.py -E True --var="njets" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # # python ../ssdilep/scripts/merge.py -E True --var="nbjets" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # # python ../ssdilep/scripts/merge.py -E True --var="NPV" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -E True --var="met_trk_et" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead e)" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead e)" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_third_pt_2" --xlabel="p_{T}(third e)" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_lead_eta_2" --xlabel="#eta(lead e)" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead e)" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_third_eta_2" --xlabel="#eta(third e)" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_lead_phi_2" --xlabel="#phi(lead e)" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead e)" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -E True --var="el_third_phi_2" --xlabel="#phi(third e)" --reg="threeElectron-VR" --lab="3LVR" --tag="threeEleVR" --samples="diboson" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral"
# # ## two + three ele SR
# # python ../ssdilep/scripts/merge.py -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="SR-ele-SR" --lab="SRee" --tag="SR1" --samples="SSVR" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="SR-ele-SR" --lab="SRee" --tag="SR1" --samples="SSVR" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="SR-ele-SR" --reg="SR-ele-SR" --lab="SRee" --tag="SR1" --samples="SSVR" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonPt_SR_2" --xlabel="p_{T}(e^{#pm}e^{#pm})" --reg="SR-ele-SR" --reg="SR-ele-SR" --lab="SRee" --tag="SR1" --samples="SSVR" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # # python ../ssdilep/scripts/merge.py -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}e^{#pm})" --reg="SR-ele-SR" --reg="SR-ele-SR" --lab="SRee" --tag="SR1" --samples="SSVR" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="nelectrons" --reg="SR-ele-SR" --reg="SR-ele-SR" --lab="SRee" --tag="SR1" --samples="SSVR" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="nsspairs" --reg="SR-ele-SR" --reg="SR-ele-SR" --lab="SRee" --tag="SR1" --samples="SSVR" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="NPV" --reg="SR-ele-SR" --reg="SR-ele-SR" --lab="SRee" --tag="SR1" --samples="SSVR" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="met_trk_et" --reg="SR-ele-SR" --reg="SR-ele-SR" --lab="SRee" --tag="SR1" --samples="SSVR" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead e)" --reg="SR-ele-SR" --reg="SR-ele-SR" --lab="SRee" --tag="SR1" --samples="SSVR" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead e)" --reg="SR-ele-SR" --reg="SR-ele-SR" --lab="SRee" --tag="SR1" --samples="SSVR" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_eta_2" --xlabel="#eta(lead e)" --reg="SR-ele-SR" --reg="SR-ele-SR" --lab="SRee" --tag="SR1" --samples="SSVR" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead e)" --reg="SR-ele-SR" --reg="SR-ele-SR" --lab="SRee" --tag="SR1" --samples="SSVR" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_phi_2" --xlabel="#phi(lead e)" --reg="SR-ele-SR" --reg="SR-ele-SR" --lab="SRee" --tag="SR1" --samples="SSVR" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead e)" --reg="SR-ele-SR" --reg="SR-ele-SR" --lab="SRee" --tag="SR1" --samples="SSVR" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # ## two ele SR
# # python ../ssdilep/scripts/merge.py -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="two-ele-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="two-ele-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="two-ele-dR-SR" --lab="SR 1P2L (dR cut only)" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonPt_SR_2" --xlabel="p_{T}(e^{#pm}e^{#pm})" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonPt_SR_2" --xlabel="p_{T}(e^{#pm}e^{#pm})" --reg="two-ele-dR-SR" --lab="SR 1P2L (dR cut only)" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # # python ../ssdilep/scripts/merge.py -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}e^{#pm})" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="nelectrons" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="NPV" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="met_trk_et" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead e)" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead e)" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_eta_2" --xlabel="#eta(lead e)" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead e)" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_phi_2" --xlabel="#phi(lead e)" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead e)" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # # ## optimized two ele SR
# # python ../ssdilep/scripts/merge.py -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="two-ele-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="invMassSR2EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="two-ele-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=False --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="two-ele-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonPt_SR_2" --xlabel="p_{T}(e^{#pm}e^{#pm})" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # # python ../ssdilep/scripts/merge.py -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}e^{#pm})" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="nelectrons" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="nsspairs" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="NPV" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="met_trk_et" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead e)" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead e)" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_eta_2" --xlabel="#eta(lead e)" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead e)" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_phi_2" --xlabel="#phi(lead e)" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead e)" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # # ## three ele SR
# # python ../ssdilep/scripts/merge.py -E True --var="invMassSR3ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="invMassSR3EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="three-ele-dR-SR" --lab="SR 1P3L (dR cut only)" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonPt_SR" --xlabel="p_{T}(e^{#pm}e^{#pm})" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonPt_SR" --xlabel="p_{T}(e^{#pm}e^{#pm})" --reg="three-ele-dR-SR" --lab="SR 1P3L (dR cut only)" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="invMassOS1" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="invMassOS2" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # # python ../ssdilep/scripts/merge.py -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}e^{#pm})" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="nelectrons" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="nsspairs" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="njets" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="nbjets" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="NPV" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="met_trk_et" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead e)" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead e)" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_third_pt_SR" --xlabel="p_{T}(third e)" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_eta_2" --xlabel="#eta(lead e)" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead e)" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_third_eta_2" --xlabel="#eta(third e)" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_phi_2" --xlabel="#phi(lead e)" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead e)" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_third_phi_2" --xlabel="#phi(third e)" --reg="three-ele-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # # ## optimized three ele SR
# # python ../ssdilep/scripts/merge.py -E True --var="invMassSR3ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="invMassSR3EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="HT" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="invMassOS1" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="invMassOS2" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="ZbosonPt_SR" --xlabel="p_{T}(e^{#pm}e^{#pm})" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRee 100
# # # python ../ssdilep/scripts/merge.py -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}e^{#pm})" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="nelectrons" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="nsspairs" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="njets" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="nbjets" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="NPV" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="met_trk_et" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead e)" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead e)" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_third_pt_SR" --xlabel="p_{T}(third e)" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_eta_2" --xlabel="#eta(lead e)" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead e)" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_third_eta_2" --xlabel="#eta(third e)" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_lead_phi_2" --xlabel="#phi(lead e)" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead e)" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRee 100
# # python ../ssdilep/scripts/merge.py -E True --var="el_third_phi_2" --xlabel="#phi(third e)" --reg="three-ele-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./electronChannel" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True


# # python ../ssdilep/scripts/merge.py -E True --var="invMass_fit" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="opposite-sign-bveto-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="allSamples" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py -E True --var="invMass_2" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="allSamples" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py -E True --var="invMass_fit" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="OSTTCR" --samples="allSamples" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py -E True --var="invMass_3" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="SSTTVR" --samples="allSamples" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py -E True --var="invMass_4" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="diboson-CR" --lab="DBCR" --tag="DBCR" --samples="allSamples" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py -E True --var="invMass_4" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="threeElectron-VR" --lab="3LVR" --tag="DBCRZveto" --samples="allSamples" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"

# # python ../ssdilep/scripts/merge.py -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="SR-ele-SR" --lab="SRee" --tag="SR1" --samples="allSamples" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal=True --rebinToEq="True" --varName="obs_mee"


# # # python ../ssdilep/scripts/merge.py -E True --var="invMassSR3EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="three-ele-optimized-SR" --lab="SR 1P3L" --tag="3ELSR" --samples="allSamples" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal=True --rebinToEq="True" --varName="obs_mee"
# # # python ../ssdilep/scripts/merge.py -E True --var="invMassSR2EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="two-ele-optimized-SR" --lab="SR 1P2L" --tag="2ELSR" --samples="allSamples" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal=True --rebinToEq="True" --varName="obs_mee"
# # # python ../ssdilep/scripts/merge.py -E True --var="invMassSR2EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="two-ele-SR" --tag="2ELSR" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal="True" --rebinToEq="True" --varName="obs_mee"
# # # python ../ssdilep/scripts/merge.py -E True --var="invMassSR3EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="three-ele-SR" --lab="SR 1P3L" --tag="3ELSR" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal="True" --rebinToEq="True" --varName="obs_mee"
# # # python ../ssdilep/scripts/merge.py -E True --var="el_third_pt_SR" --xlabel="p_{T}(third e)" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="three-ele-SR" --lab="SR 1P3L" --tag="3ELSR" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal="True" --rebinToEq="True" --varName="obs_pt"

