# python ../ssdilep/scripts/merge.py -y "True" --rebinToEq="True" --varName="obs_mjj" --elesys="True" --var="Mjj2" --reg="electron-SS-Z-CR" --lab="SS ZCR ee" --tag="SSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_003_SYS" --output="./HN_003_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y "True" --rebinToEq="True" --varName="obs_mjj" --elesys="True" --var="Mjj4" --reg="electron-SS-Z-VR" --lab="SS ZVR ee" --tag="SSZVRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_003_SYS" --output="./HN_003_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y "True" --rebinToEq="True" --varName="obs_mjj" -S True  --elesys="True" --var="Mjj3" --reg="electron-SS-Z-SR" --lab="SS ZSR ee" --tag="SSZSRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_003_SYS" --output="./HN_003_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"

# python ../ssdilep/scripts/merge.py -y "True" --rebinToEq="True" --varName="obs_HT" --elesys="True" --musys="True" --var="HT2Lep2Jet_8" --reg="electron-SS-Z-CR" --lab="SS ZCR ee" --tag="SSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_003_SYS" --output="./HN_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y "True" --rebinToEq="True" --varName="obs_HT" --elesys="True" --musys="True" --var="HT2Lep2Jet_5" --reg="electron-SS-Z-VR" --lab="SS ZVR ee" --tag="SSZVRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_003_SYS" --output="./HN_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y "True" --rebinToEq="True" --varName="obs_HT" --elesys="True" --musys="True" --var="HT2Lep2Jet_5s" --reg="electron-SS-Z-SR" --lab="SS ZSR ee" --tag="SSZSRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_003_SYS" --output="./HN_SYS_root" --makeplot=False --fakest="FakeFactorGeneral" -S True

# python ../ssdilep/scripts/merge.py -y "True" --varName="obs_HT" --rebinToEq="True" --elesys="True" --musys="True" --var="HT2Lep2Jet_5"  --tag="SSZCRmm" --reg="muon-SS-Z-CR" --lab="SS ZCR #mu#mu" --tag="SSZCRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_006_SYS" --output="./HN_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y "True" --varName="obs_HT" --rebinToEq="True" --elesys="True" --musys="True" --var="HT2Lep2Jet_5"  --tag="SSZVRmm" --reg="muon-SS-Z-VR" --lab="SS ZVR #mu#mu" --tag="SSZVRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_006_SYS" --output="./HN_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -y "True" --varName="obs_HT" --rebinToEq="True" --elesys="True" --musys="True" --var="HT2Lep2Jet_5s" --tag="SSZSRmm" --reg="muon-SS-Z-SR" --lab="SS ZSR #mu#mu" --tag="SSZSRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_006_SYS" --output="./HN_SYS_root" --makeplot=False --fakest="FakeFactorGeneral" -S True
