# # #!bin/bash

# ##SSVR
python ../ssdilep/scripts/merge.py -M True --var="invMass_mu" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="DR4" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="ZbosonEta_2" --xlabel="#eta(Z)" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="nleptons" --xlabel="N(#mu)" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="nsspairs" --xlabel="N(#mu^{#pm}#mu^{#pm})" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="NPV" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="met_trk_et" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_lead_pt_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_sublead_pt_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_lead_eta_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_sublead_eta_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_lead_phi_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_sublead_phi_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# ##diboson
python ../ssdilep/scripts/merge.py -M True --var="invMass_mu" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="DR4" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="invMassOS1" --xlabel="lead m(#mu^{#pm}#mu^{#mp}) [GeV]"  --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="invMassOS2" --xlabel="sublead m(#mu^{#pm}#mu^{#mp}) [GeV]"  --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="ZbosonEta_2" --xlabel="#eta(Z)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="nleptons" --xlabel="N(#mu)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="njets" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="nbjets" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="NPV" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="met_trk_et" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_lead_pt_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_sublead_pt_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_third_pt_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_lead_eta_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_sublead_eta_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_third_eta_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_lead_phi_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_sublead_phi_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_third_phi_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# # ##three electron
python ../ssdilep/scripts/merge.py -M True --var="invMass_mu2" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="DR4" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="invMassOS1" --xlabel="lead m(#mu^{#pm}#mu^{#mp}) [GeV]" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="invMassOS2" --xlabel="sublead m(#mu^{#pm}#mu^{#mp}) [GeV]" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="ZbosonEta_2" --xlabel="#eta(Z)" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="nleptons" --xlabel="N(#mu)" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="njets" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="nbjets" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="NPV" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="met_trk_et" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_lead_pt_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_sublead_pt_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_third_pt_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_lead_eta_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_sublead_eta_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_third_eta_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_lead_phi_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_sublead_phi_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="el_third_phi_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# # ## two + three ele SR
python ../ssdilep/scripts/merge.py -M True --var="invMassSR2ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="DR2" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_SR_2" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="ZbosonEta_2" --xlabel="#eta(Z)" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="nleptons" --xlabel="N(#mu)" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="nsspairs" --xlabel="N(#mu^{#pm}#mu^{#pm})" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="NPV" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="met_trk_et" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_pt_2" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_pt_2" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_eta_2" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_eta_2" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_phi_2" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_phi_2" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# # ## two ele SR
python ../ssdilep/scripts/merge.py -M True --var="invMassSR2ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="DR2" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="two-muon-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="two-muon-dR-SR" --lab="SR1-2 (dR cut only)" --tag="SR1-2" --samples="SSVR_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_SR_2" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_SR_2" --reg="two-muon-dR-SR" --lab="SR1-2 (dR cut only)" --tag="SR1-2" --samples="SSVR_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="ZbosonEta_2" --xlabel="#eta(Z)" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="nleptons" --xlabel="N(#mu)" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="NPV" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="met_trk_et" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_pt_2" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_pt_2" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_eta_2" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_eta_2" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_phi_2" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_phi_2" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# # # ## optimized two ele SR
python ../ssdilep/scripts/merge.py -M True --var="invMassSR2ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="invMassSR2EL" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=False --branching 0
python ../ssdilep/scripts/merge.py -M True --var="DR2" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="two-muon-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_SR_2" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="ZbosonEta_2" --xlabel="#eta(Z)" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="nleptons" --xlabel="N(#mu)" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="nsspairs" --xlabel="N(#mu^{#pm}#mu^{#pm})" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="NPV" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="met_trk_et" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_pt_2" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_pt_2" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_eta_2" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_eta_2" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_phi_2" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_phi_2" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# # # ## three ele SR
python ../ssdilep/scripts/merge.py -M True --var="invMassSR3ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="invMassSR3EL" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="DR2" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="three-muon-dR-SR" --lab="SR1-3 (dR cut only)" --tag="SR1-3" --samples="dibosonFit_mu" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_SR" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_SR" --reg="three-muon-dR-SR" --lab="SR1-3 (dR cut only)" --tag="SR1-3" --samples="dibosonFit_mu" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="invMassOS1" --xlabel="lead m(#mu^{#pm}#mu^{#mp}) [GeV]" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="invMassOS2" --xlabel="sublead m(#mu^{#pm}#mu^{#mp}) [GeV]" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="ZbosonEta_2" --xlabel="#eta(Z)" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="nleptons" --xlabel="N(#mu)" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="nsspairs" --xlabel="N(#mu^{#pm}#mu^{#pm})" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="njets" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="nbjets" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="NPV" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="met_trk_et" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_pt_2" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_pt_2" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_third_pt_SR" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_eta_2" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_eta_2" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_third_eta_2" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_phi_2" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_phi_2" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_third_phi_2" --reg="three-muon-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# # # ## optimized three ele SR
python ../ssdilep/scripts/merge.py -M True --var="invMassSR3ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="invMassSR3EL" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="DR2" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="HT" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="invMassOS1" --xlabel="lead m(#mu^{#pm}#mu^{#mp}) [GeV]" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="invMassOS2" --xlabel="sublead m(#mu^{#pm}#mu^{#mp}) [GeV]" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_SR" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="ZbosonEta_2" --xlabel="#eta(Z)" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="nleptons" --xlabel="N(#mu)" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="nsspairs" --xlabel="N(#mu^{#pm}#mu^{#pm})" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="njets" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="nbjets" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="NPV" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
python ../ssdilep/scripts/merge.py -M True --var="met_trk_et" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_pt_2" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_pt_2" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_third_pt_SR" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_eta_2" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_eta_2" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_third_eta_2" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_phi_2" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_phi_2" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0
# python ../ssdilep/scripts/merge.py -M True --var="el_third_phi_2" --reg="three-muon-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --branching 0


# python ../ssdilep/scripts/merge.py -M True --var="invMass_fit" --xlabel="m(#mu^{#pm}#mu^{#mp}) [GeV]" --reg="opposite-sign-bveto-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# python ../ssdilep/scripts/merge.py -M True --var="invMass_2" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="same-sign-CR" --tag="SSVR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# python ../ssdilep/scripts/merge.py -M True --var="invMass_fit" --xlabel="m(#mu^{#pm}#mu^{#mp}) [GeV]" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="OSTTCR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# python ../ssdilep/scripts/merge.py -M True --var="invMass_3" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="SSTTVR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# python ../ssdilep/scripts/merge.py -M True --var="invMass_4" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="diboson-CR" --lab="DBCR" --tag="DBCR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# python ../ssdilep/scripts/merge.py -M True --var="invMass_4" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="threeLep-VR" --lab="DBVR" --tag="DBCRZveto" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"

# python ../ssdilep/scripts/merge.py -M True --var="invMassSR2ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="SR-muon-SR" --lab="SR1" --tag="SR1" --samples="allSamples" --icut="8" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal=True --rebinToEq="True" --varName="obs_mee"


# # python ../ssdilep/scripts/merge.py -M True --var="invMassSR3EL" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR" --lab="SR1-3" --tag="3ELSR" --samples="allSamples" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal=True --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py -M True --var="invMassSR2EL" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-optimized-SR" --lab="SR1-2" --tag="2ELSR" --samples="allSamples" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal=True --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py -M True --var="invMassSR2EL" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-SR" --tag="2ELSR" --samples="SSVR_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal="True" --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py -M True --var="invMassSR3EL" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-SR" --lab="SR1-3" --tag="3ELSR" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal="True" --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py -M True --var="el_third_pt_SR" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-SR" --lab="SR1-3" --tag="3ELSR" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal="True" --rebinToEq="True" --varName="obs_pt"

