#!bin/bash

# Strings are passed to the scrieta but this is redundant!

python ../ssdilep/scripts/merge.py --var="invMass" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="2" --input="/afs/f9.ijs.si/home/miham/AllR_v3_001" --output="./OSCR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="ZbosonPt" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="2" --input="/afs/f9.ijs.si/home/miham/AllR_v3_001" --output="./OSCR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="ZbosonEta" --xlabel="#eta(Z)" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="2" --input="/afs/f9.ijs.si/home/miham/AllR_v3_001" --output="./OSCR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="nelectrons" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="2" --input="/afs/f9.ijs.si/home/miham/AllR_v3_001" --output="./OSCR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="NPV" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="2" --input="/afs/f9.ijs.si/home/miham/AllR_v3_001" --output="./OSCR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="met_trk_et" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="2" --input="/afs/f9.ijs.si/home/miham/AllR_v3_001" --output="./OSCR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="met_clus_et" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="2" --input="/afs/f9.ijs.si/home/miham/AllR_v3_001" --output="./OSCR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="el_lead_pt" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="2" --input="/afs/f9.ijs.si/home/miham/AllR_v3_001" --output="./OSCR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="el_sublead_pt" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="2" --input="/afs/f9.ijs.si/home/miham/AllR_v3_001" --output="./OSCR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="el_lead_eta" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="2" --input="/afs/f9.ijs.si/home/miham/AllR_v3_001" --output="./OSCR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="el_sublead_eta" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="2" --input="/afs/f9.ijs.si/home/miham/AllR_v3_001" --output="./OSCR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="el_lead_phi" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="2" --input="/afs/f9.ijs.si/home/miham/AllR_v3_001" --output="./OSCR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="el_sublead_phi" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="2" --input="/afs/f9.ijs.si/home/miham/AllR_v3_001" --output="./OSCR" --makeplot=True --fakest="FakeFactorGeneral"
