#!bin/bash

# Strings are passed to the scrieta but this is redundant!  noCHF

python ../ssdilep/scripts/merge.py --var="invMass_4" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="invMassOS1" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="invMassOS2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="ZbosonPt_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="ZbosonEta_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="nelectrons" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="njets" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="nbjets" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="NPV" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="met_trk_et" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="met_clus_et" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="el_lead_pt_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="el_sublead_pt_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="el_third_pt_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="el_lead_eta_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="el_sublead_eta_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="el_third_eta_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="el_lead_phi_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="el_sublead_phi_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py --var="el_third_phi_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="1" --input="/afs/f9.ijs.si/home/miham/ThreeEleVR36_5" --output="./threeEleVR" --makeplot=True --fakest="FakeFactorGeneral"
