# # #!bin/bash

python ../ssdilep/scripts/merge.py  --blind=400 -y "True" --elesys="True" --var="invMassZCRbroad" --xlabel="m(ee) [GeV]" --reg="electron-OS-Z-BROAD" --lab="OS ee" --tag="OSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_006_SYS" --output="./HN_006_SYS" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --blind=400 -y "True" --musys="True" --var="invMassZCRbroad" --xlabel="m(#mu#mu) [GeV]" --reg="muon-OS-Z-BROAD" --lab="OS #mu#mu" --tag="OSZCRee" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_006_SYS" --output="./HN_006_SYS" --makeplot=True --fakest="FakeFactorGeneral"

# python ../ssdilep/scripts/merge.py  --blind=400 -y "True" --elesys="True" --var="invMassZCRpeak" --xlabel="m(ee) [GeV]" --reg="electron-OS-Z-BROAD" --lab="OS ZCR ee" --tag="OSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_006_SYS" --output="./HN_006_SYS" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --blind=400 -y "True" --musys="True" --var="invMassZCRpeak" --xlabel="m(#mu#mu) [GeV]" --reg="muon-OS-Z-BROAD" --lab="OS ZCR #mu#mu" --tag="OSZCRee" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_006_SYS" --output="./HN_006_SYS" --makeplot=True --fakest="FakeFactorGeneral"

# python ../ssdilep/scripts/merge.py  --blind=400 -y "True" --elesys="True" --var="invMassZVR" --xlabel="m(ee) [GeV]" --reg="electron-OS-Z-BROAD" --lab="OS ZVR ee" --tag="OSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_006_SYS" --output="./HN_006_SYS" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --blind=400 -y "True" --musys="True" --var="invMassZVR" --xlabel="m(#mu#mu) [GeV]" --reg="muon-OS-Z-BROAD" --lab="OS ZVR #mu#mu" --tag="OSZCRee" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_006_SYS" --output="./HN_006_SYS" --makeplot=True --fakest="FakeFactorGeneral"

# python ../ssdilep/scripts/merge.py  --blind=400 -y "True" --elesys="True" --var="invMassZSR2" --xlabel="m(ee) [GeV]" --reg="electron-OS-Z-BROAD" --lab="OS ZSR ee" --tag="OSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_006_SYS" --output="./HN_006_SYS" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --blind=400 -y "True" --musys="True" --var="invMassZSR2" --xlabel="m(#mu#mu) [GeV]" --reg="muon-OS-Z-BROAD" --lab="OS ZSR #mu#mu" --tag="OSZCRee" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_006_SYS" --output="./HN_006_SYS" --makeplot=True --fakest="FakeFactorGeneral"
