# # #!bin/bash

# # ##OSCR
# # python ../ssdilep/scripts/merge.py --var="invMass" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py --var="ZbosonPt" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py --var="ZbosonEta" --xlabel="#eta(Z)" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py --var="nelectrons" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py --var="NPV" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py --var="met_trk_et" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py --var="el_lead_pt" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py --var="el_sublead_pt" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py --var="el_lead_eta" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py --var="el_sublead_eta" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py --var="el_lead_phi" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py --var="el_sublead_phi" --reg="opposite-sign-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="OSCR" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# # ##OSCR b veto
# python ../ssdilep/scripts/merge.py --var="invMass" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="DR" --xlabel="#DeltaR(e^{#pm}e^{#mp})" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="ZbosonPt" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="ZbosonEta" --xlabel="#eta(Z)" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="nelectrons" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="NPV" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="met_trk_et" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_pt" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_pt" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_eta" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_eta" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_phi" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_phi" --reg="opposite-sign-bveto-CR" --lab="OSCR-bveto" --samples="OSCR" --tag="OSCR-bveto" --samples="OSCR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# ##SSVR
# python ../ssdilep/scripts/merge.py --var="invMass_2" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="DR4" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="ZbosonPt_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="ZbosonEta_2" --xlabel="#eta(Z)" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="nelectrons" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="NPV" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="met_trk_et" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_pt_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_pt_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_eta_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_eta_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_phi_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_phi_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# # ##ttbar OSCR
# python ../ssdilep/scripts/merge.py --var="invMass" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="DR4" --xlabel="#DeltaR(e^{#pm}e^{#mp})" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="ZbosonPt" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="ZbosonEta" --xlabel="#eta(Z)" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="nelectrons" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="NPV" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="met_trk_et" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_pt" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_pt" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_eta" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_eta" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_phi" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_phi" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbar" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# ##ttbar SSVR
# python ../ssdilep/scripts/merge.py --var="invMass_3" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="DR4" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="ZbosonPt_2" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="ZbosonEta_2" --xlabel="#eta(Z)" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="nelectrons" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="NPV" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="met_trk_et" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_pt_2" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_pt_2" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_eta_2" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_eta_2" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_phi_2" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_phi_2" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="TTBAR" --samples="ttbarss" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# ##diboson
# python ../ssdilep/scripts/merge.py --var="invMass_4" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="DR4" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="invMassOS1" --xlabel="m(e^{#pm}e^{#mp}) [GeV]"  --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="invMassOS2" --xlabel="m(e^{#pm}e^{#mp}) [GeV]"  --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="ZbosonPt_2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="ZbosonEta_2" --xlabel="#eta(Z)" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="nelectrons" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="njets" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="nbjets" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="NPV" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="met_trk_et" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_pt_2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_pt_2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_third_pt_2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_eta_2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_eta_2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_third_eta_2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_phi_2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_phi_2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_third_phi_2" --reg="diboson-CR" --lab="diboson CR" --tag="diboson" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# # ##three electron
# python ../ssdilep/scripts/merge.py --var="invMass_4" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="DR4" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="invMassOS1" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="invMassOS2" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="ZbosonPt_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="ZbosonEta_2" --xlabel="#eta(Z)" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="nelectrons" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="njets" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="nbjets" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="NPV" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="met_trk_et" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_pt_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_pt_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_third_pt_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_eta_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_eta_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_third_eta_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_lead_phi_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_sublead_phi_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py --var="el_third_phi_2" --reg="threeElectron-VR" --lab="three electron VR" --tag="threeEleVR" --samples="diboson" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral"
# ## two + three ele SR
# python ../ssdilep/scripts/merge.py --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="SR1-ele-SR" --lab="SR1" --tag="SR1" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="invMassSR2EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="SR1-ele-SR" --lab="SR1" --tag="SR1" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="DR2" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="SR1-ele-SR" --lab="SR1" --tag="SR1" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="HTmet" --xlabel="#Sigma p_{T} + MET [GeV]" --reg="SR1-ele-SR" --reg="SR1-ele-SR" --lab="SR1" --tag="SR1" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="SR1-ele-SR" --reg="SR1-ele-SR" --lab="SR1" --tag="SR1" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="mTtot" --xlabel="m_{T} [GeV]" --reg="SR1-ele-SR"  --reg="SR1-ele-SR" --lab="SR1" --tag="SR1" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="ZbosonPt_SR_2" --reg="SR1-ele-SR" --reg="SR1-ele-SR" --lab="SR1" --tag="SR1" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="ZbosonEta_2" --xlabel="#eta(Z)" --reg="SR1-ele-SR" --reg="SR1-ele-SR" --lab="SR1" --tag="SR1" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="nelectrons" --reg="SR1-ele-SR" --reg="SR1-ele-SR" --lab="SR1" --tag="SR1" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="NPV" --reg="SR1-ele-SR" --reg="SR1-ele-SR" --lab="SR1" --tag="SR1" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="met_trk_et" --reg="SR1-ele-SR" --reg="SR1-ele-SR" --lab="SR1" --tag="SR1" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_lead_pt_2" --reg="SR1-ele-SR" --reg="SR1-ele-SR" --lab="SR1" --tag="SR1" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_sublead_pt_2" --reg="SR1-ele-SR" --reg="SR1-ele-SR" --lab="SR1" --tag="SR1" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_lead_eta_2" --reg="SR1-ele-SR" --reg="SR1-ele-SR" --lab="SR1" --tag="SR1" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_sublead_eta_2" --reg="SR1-ele-SR" --reg="SR1-ele-SR" --lab="SR1" --tag="SR1" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_lead_phi_2" --reg="SR1-ele-SR" --reg="SR1-ele-SR" --lab="SR1" --tag="SR1" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_sublead_phi_2" --reg="SR1-ele-SR" --reg="SR1-ele-SR" --lab="SR1" --tag="SR1" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# ## two ele SR
# python ../ssdilep/scripts/merge.py --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="invMassSR2EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="DR2" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="HTmet" --xlabel="#Sigma p_{T} + MET [GeV]" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="two-ele-dR-SR" --lab="SR1-2 (dR cut only)" --tag="SR1-2" --samples="SSVR" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="mTtot" --xlabel="m_{T} [GeV]" --reg="two-ele-SR"  --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="ZbosonPt_SR_2" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="ZbosonPt_SR_2" --reg="two-ele-dR-SR" --lab="SR1-2 (dR cut only)" --tag="SR1-2" --samples="SSVR" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="ZbosonEta_2" --xlabel="#eta(Z)" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="nelectrons" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="NPV" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="met_trk_et" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_lead_pt_2" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_sublead_pt_2" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_lead_eta_2" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="el_sublead_eta_2" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="el_lead_phi_2" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_sublead_phi_2" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# # ## optimized two ele SR
# python ../ssdilep/scripts/merge.py --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="two-ele-optimized-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="8" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="invMassSR2EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="two-ele-optimized-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="8" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=False
# python ../ssdilep/scripts/merge.py --var="DR2" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="two-ele-optimized-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="ZbosonPt_SR_2" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="ZbosonEta_2" --xlabel="#eta(Z)" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="nelectrons" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="NPV" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="met_trk_et" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_lead_pt_2" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_sublead_pt_2" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_lead_eta_2" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="el_sublead_eta_2" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="el_lead_phi_2" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_sublead_phi_2" --reg="two-ele-optimized-SR" --reg="two-ele-optimized-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# # ## three ele SR
# python ../ssdilep/scripts/merge.py --var="invMassSR3ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="invMassSR3EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="DR2" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="three-ele-dR-SR" --lab="SR1-3 (dR cut only)" --tag="SR1-3" --samples="dibosonFit" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="HTmet" --xlabel="#Sigma p_{T} + MET [GeV]" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="mTtot" --xlabel="m_{T} [GeV]" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="ZbosonPt_SR" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="ZbosonPt_SR" --reg="three-ele-dR-SR" --lab="SR1-3 (dR cut only)" --tag="SR1-3" --samples="dibosonFit" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="invMassOS1" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="invMassOS2" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="ZbosonEta_2" --xlabel="#eta(Z)" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="nelectrons" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="njets" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="nbjets" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="NPV" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="met_trk_et" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_lead_pt_2" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_sublead_pt_2" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_third_pt_SR" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_lead_eta_2" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_sublead_eta_2" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_third_eta_2" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_lead_phi_2" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_sublead_phi_2" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_third_phi_2" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# # ## optimized three ele SR
# python ../ssdilep/scripts/merge.py --var="invMassSR3ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="8" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="invMassSR3EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="8" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="DR2" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="HT" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="invMassOS1" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="invMassOS2" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="ZbosonPt_SR" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="ZbosonEta_2" --xlabel="#eta(Z)" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="nelectrons" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="njets" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="nbjets" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="NPV" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="met_trk_et" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_lead_pt_2" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_sublead_pt_2" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_third_pt_SR" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_lead_eta_2" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_sublead_eta_2" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_third_eta_2" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_lead_phi_2" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_sublead_phi_2" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="el_third_phi_2" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True


python ../ssdilep/scripts/merge.py --var="invMass_fit" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="opposite-sign-bveto-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
python ../ssdilep/scripts/merge.py --var="invMass_2" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="same-sign-CR" --tag="SSVR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
python ../ssdilep/scripts/merge.py --var="invMass_fit" --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="OSTTCR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
python ../ssdilep/scripts/merge.py --var="invMass_3" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="SSTTVR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
python ../ssdilep/scripts/merge.py --var="invMass_4" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="diboson-CR" --lab="diboson CR" --tag="DBCR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
python ../ssdilep/scripts/merge.py --var="invMass_4" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="threeElectron-VR" --lab="three electron VR" --tag="DBCRZveto" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"

python ../ssdilep/scripts/merge.py --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="SR1-ele-SR" --lab="SR1" --tag="SR1" --samples="allSamples" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020_root" --makeplot=False --fakest="FakeFactorGeneral" --signal=True --rebinToEq="True" --varName="obs_mee"


# # python ../ssdilep/scripts/merge.py --var="invMassSR3EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="3ELSR" --samples="allSamples" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020_root" --makeplot=False --fakest="FakeFactorGeneral" --signal=True --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py --var="invMassSR2EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="two-ele-optimized-SR" --lab="SR1-2" --tag="2ELSR" --samples="allSamples" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020/" --output="./AllR_v3_020_root" --makeplot=False --fakest="FakeFactorGeneral" --signal=True --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py --var="invMassSR2EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="two-ele-SR" --tag="2ELSR" --samples="SSVR" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020_root" --makeplot=False --fakest="FakeFactorGeneral" --signal="True" --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py --var="invMassSR3EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="three-ele-SR" --lab="SR1-3" --tag="3ELSR" --samples="dibosonFit" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020_root" --makeplot=False --fakest="FakeFactorGeneral" --signal="True" --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py --var="el_third_pt_SR" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="three-ele-SR" --lab="SR1-3" --tag="3ELSR" --samples="dibosonFit" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_v3_020" --output="./AllR_v3_020_root" --makeplot=False --fakest="FakeFactorGeneral" --signal="True" --rebinToEq="True" --varName="obs_pt"

