# # # #!bin/bash

# # ##SSVR
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMass_3"        --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="HT" --xlabel="#Sigma p_{T} [GeV]"         --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="DR4"              --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_2"       --xlabel="p_{T}(e^{#pm}#mu^{#pm}) [GeV]" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonEta_2"      --xlabel="#eta(e^{#pm}#mu^{#pm})" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="nleptons"         --xlabel="N(l)" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="nsspairs"         --xlabel="N(e^{#pm}#mu^{#pm})" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="NPV"              --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="met_trk_et"       --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead l) [GeV]"     --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead l) [GeV]"  --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_eta_2" --xlabel="#eta(lead l)"    --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead l)" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_phi_2" --xlabel="#phi(lead l)"    --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead l)" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# # # ##diboson
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMass_DB" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="HT2" --xlabel="#Sigma p_{T} [GeV]"         --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="DR4" --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassOS1" --xlabel="lead m(e^{#pm}#mu^{#pm}) [GeV]"  --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassOS2" --xlabel="sublead m(e^{#pm}#mu^{#pm}) [GeV]"  --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_2" --xlabel="p_{T}(e^{#pm}#mu^{#pm}) [GeV]" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}#mu^{#pm})" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="nleptons" --xlabel="N(l)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="njets" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="nbjets" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="NPV" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="met_trk_et" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead l) [GeV]" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead l) [GeV]" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_pt_2" --xlabel="p_{T}(third l) [GeV]" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_eta_2" --xlabel="#eta(lead l)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead l)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_eta_2" --xlabel="#eta(third l)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_phi_2" --xlabel="#phi(lead l)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead l)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_phi_2" --xlabel="#phi(third l)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# # # # ##three electron
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMass_4" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="HT2" --xlabel="#Sigma p_{T} [GeV]"          --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="DR4" --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassOS1" --xlabel="lead m(e^{#pm}#mu^{#pm}) [GeV]" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassOS2" --xlabel="sublead m(e^{#pm}#mu^{#pm}) [GeV]" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_2" --xlabel="p_{T}(e^{#pm}#mu^{#pm}) [GeV]" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}#mu^{#pm})" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="nleptons" --xlabel="N(l)" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -M True -E True --var="njets" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -M True -E True --var="nbjets" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -M True -E True --var="NPV" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="met_trk_et" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead l) [GeV]" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead l) [GeV]" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_pt_2" --xlabel="p_{T}(third l) [GeV]" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_eta_2" --xlabel="#eta(lead l)" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead l)" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_eta_2" --xlabel="#eta(third l)" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_phi_2" --xlabel="#phi(lead l)" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead l)" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_phi_2" --xlabel="#phi(third l)" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# # # ## two + three ele SR
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="HT" --xlabel="#Sigma p_{T} [GeV]"         --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_SR_2" --xlabel="p_{T}(e^{#pm}#mu^{#pm}) [GeV]" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}#mu^{#pm})" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="nleptons" --xlabel="N(l)" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="nsspairs" --xlabel="N(e^{#pm}#mu^{#pm})" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="NPV" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="met_trk_et" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead l)" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead l)" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_eta_2" --xlabel="#eta(lead l)" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead l)" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_phi_2" --xlabel="#phi(lead l)" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead l)" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # # # ## two ele SR
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="two-leptons-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="two-leptons-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="two-leptons-SR" --reg="two-leptons-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="two-lepton-dR-SR" --lab="SR 1P2L (dR cut only)" --tag="SR1-2" --samples="SSVR_emu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_SR_2" --xlabel="p_{T}(e^{#pm}#mu^{#pm}) [GeV]" --reg="two-leptons-SR" --reg="two-leptons-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_SR_2" --xlabel="p_{T}(e^{#pm}#mu^{#pm}) [GeV]" --reg="two-lepton-dR-SR" --lab="SR 1P2L (dR cut only)" --tag="SR1-2" --samples="SSVR_emu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}#mu^{#pm})" --reg="two-leptons-SR" --reg="two-leptons-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="nleptons" --xlabel="N(l)" --reg="two-leptons-SR" --reg="two-leptons-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="NPV" --reg="two-leptons-SR" --reg="two-leptons-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="met_trk_et" --reg="two-leptons-SR" --reg="two-leptons-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead l)" --reg="two-leptons-SR" --reg="two-leptons-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead l)" --reg="two-leptons-SR" --reg="two-leptons-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_eta_2" --xlabel="#eta(lead l)" --reg="two-leptons-SR" --reg="two-leptons-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead l)" --reg="two-leptons-SR" --reg="two-leptons-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_phi_2" --xlabel="#phi(lead l)" --reg="two-leptons-SR" --reg="two-leptons-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead l)" --reg="two-leptons-SR" --reg="two-leptons-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # # # ## optimized two ele SR
python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR2EL" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=False--BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_SR_2" --xlabel="p_{T}(e^{#pm}#mu^{#pm}) [GeV]" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}#mu^{#pm})" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="nleptons" --xlabel="N(l)" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="nsspairs" --xlabel="N(e^{#pm}#mu^{#pm})" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="NPV" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="met_trk_et" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead l)" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead l)" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_eta_2" --xlabel="#eta(lead l)" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead l)" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_phi_2" --xlabel="#phi(lead l)" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead l)" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # # # ## three ele SR
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR3ELall" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR3EL" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="three-lepton-dR-SR" --lab="SR 1P3L (dR cut only)" --tag="SR1-3" --samples="dibosonFit_mu" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_SR" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_SR" --reg="three-lepton-dR-SR" --lab="SR 1P3L (dR cut only)" --tag="SR1-3" --samples="dibosonFit_mu" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="invMassOS1" --xlabel="lead m(e^{#pm}#mu^{#pm}) [GeV]" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="invMassOS2" --xlabel="sublead m(e^{#pm}#mu^{#pm}) [GeV]" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}#mu^{#pm})" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="nleptons" --xlabel="N(l)" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="nsspairs" --xlabel="N(e^{#pm}#mu^{#pm})" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="njets" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="nbjets" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="NPV" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="met_trk_et" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead l)" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead l)" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_pt_SR" --xlabel="p_{T}(third l)" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_eta_2" --xlabel="#eta(lead l)" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead l)" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_eta_2" --xlabel="#eta(third l)" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_phi_2" --xlabel="#phi(lead l)" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead l)" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_phi_2" --xlabel="#phi(third l)" --reg="three-lepton-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # # # ## optimized three ele SR
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR3ELall" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR3EL" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="HT" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="invMassOS1" --xlabel="lead m(e^{#pm}#mu^{#pm}) [GeV]" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="invMassOS2" --xlabel="sublead m(e^{#pm}#mu^{#pm}) [GeV]" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_SR" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}#mu^{#pm})" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="nleptons" --xlabel="N(l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="nsspairs" --xlabel="N(e^{#pm}#mu^{#pm})" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="njets" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="nbjets" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="NPV" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="met_trk_et" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_pt_SR" --xlabel="p_{T}(third l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_eta_2" --xlabel="#eta(lead l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_eta_2" --xlabel="#eta(third l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_phi_2" --xlabel="#phi(lead l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_phi_2" --xlabel="#phi(third l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100