# python ../ssdilep/scripts/merge.py -y "True" --rebinToEq="True" --varName="obs_mjj" --elesys="True" --var="Mjj2" --reg="electron-SS-Z-CR" --lab="SS ZCR ee" --tag="SSZCRee" --samples="HNeeFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_003_SYS" --output="./HN_003_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y "True" --rebinToEq="True" --varName="obs_mjj" --elesys="True" --var="Mjj4" --reg="electron-SS-Z-VR" --lab="SS ZVR ee" --tag="SSZVRee" --samples="HNeeFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_003_SYS" --output="./HN_003_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y "True" --rebinToEq="True" --varName="obs_mjj" -S True  --elesys="True" --var="Mjj3" --reg="electron-SS-Z-SR" --lab="SS ZSR ee" --tag="SSZSRee" --samples="HNeeFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_003_SYS" --output="./HN_003_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"

# python ../ssdilep/scripts/merge.py -y "True" --varName="obs_Mjj" --rebinToEq="True" --elesys="True" --musys="True" --var="Mjj5" --reg="electron-SS-Z60-CR" --lab="SS ZCR ee" --tag="SSZ60CRee" --samples="HNeeFit" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_v2_052_SYS" --output="./HN_v052_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y "True" --varName="obs_Mjj" --rebinToEq="True" --elesys="True" --musys="True" --var="Mjj5" --reg="electron-SS-Z70-CR" --lab="SS ZCR ee" --tag="SSZ70CRee" --samples="HNeeFit" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_v2_052_SYS" --output="./HN_v052_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y "True" --varName="obs_Mjj" --rebinToEq="True" --elesys="True" --musys="True" --var="Mjj5" --reg="electron-SS-Z80-CR" --lab="SS ZCR ee" --tag="SSZ80CRee" --samples="HNeeFit" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_v2_052_SYS" --output="./HN_v052_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y "True" --varName="obs_Mjj" --rebinToEq="True" --elesys="True" --musys="True" --var="Mjj5" --reg="electron-SS-Z90-CR" --lab="SS ZCR ee" --tag="SSZ90CRee" --samples="HNeeFit" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_v2_052_SYS" --output="./HN_v052_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y "True" --varName="obs_Mjj" --rebinToEq="True" --elesys="True" --musys="True" --var="Mjj5" --reg="electron-SS-Z100-CR" --lab="SS ZCR ee" --tag="SSZ100CRee" --samples="HNeeFit" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_v2_052_SYS" --output="./HN_v052_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"

python ../ssdilep/scripts/merge.py -y "True" --varName="obs_Mjj" --rebinToEq="True" --elesys="True" --musys="True" --var="Mjj5" --reg="electron-SS-Z-CR" --lab="SS ZCR ee" --tag="SSZCRee" --samples="HNeeFit" --icut="5" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_v2_052_SYS" --output="./HN_v052_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -y "True" --varName="obs_HT" --rebinToEq="True" --elesys="True" --musys="True" --var="HT2Lep2Jet_8_broad" --reg="electron-SS-Z-VR" --lab="SS ZVR ee" --tag="SSZVRee" --samples="HNeeFit" --icut="5" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_v2_052_SYS" --output="./HN_v052_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -y "True" --varName="obs_HT" --rebinToEq="True" --elesys="True" --musys="True" --var="HT8s" --reg="electron-SS-Z-SR" --lab="SS ZSR ee" --tag="SSZSRee" --samples="HNeeFit" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_v2_052_SYS" --output="./HN_v052_SYS_root" --makeplot=False --fakest="FakeFactorGeneral" -S True
# python ../ssdilep/scripts/merge.py -y "True" --varName="obs_Mlljj" --noNorm="True" --rebinToEq="True" --elesys="True" --musys="True" --var="Mlljj8s" --reg="electron-SS-Z-SR" --lab="SS ZSR ee" --tag="SSZSRee" --samples="HNeeFit" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_v2_052_SYS" --output="./HN_v052_SYS_root" --makeplot=False --fakest="FakeFactorGeneral" -S True

# python ../ssdilep/scripts/merge.py -y "True" --varName="obs_Mjj" --rebinToEq="True" --elesys="True" --musys="True" --var="Mjj6"  --tag="SSZ60CRmm" --reg="muon-SS-Z60-CR" --lab="SS ZCR #mu#mu" --samples="HNmumuFit" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_v2_052_SYS" --output="./HN_v052_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y "True" --varName="obs_Mjj" --rebinToEq="True" --elesys="True" --musys="True" --var="Mjj6"  --tag="SSZ70CRmm" --reg="muon-SS-Z70-CR" --lab="SS ZCR #mu#mu" --samples="HNmumuFit" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_v2_052_SYS" --output="./HN_v052_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y "True" --varName="obs_Mjj" --rebinToEq="True" --elesys="True" --musys="True" --var="Mjj6"  --tag="SSZ80CRmm" --reg="muon-SS-Z80-CR" --lab="SS ZCR #mu#mu" --samples="HNmumuFit" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_v2_052_SYS" --output="./HN_v052_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y "True" --varName="obs_Mjj" --rebinToEq="True" --elesys="True" --musys="True" --var="Mjj6"  --tag="SSZ90CRmm" --reg="muon-SS-Z90-CR" --lab="SS ZCR #mu#mu" --samples="HNmumuFit" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_v2_052_SYS" --output="./HN_v052_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y "True" --varName="obs_Mjj" --rebinToEq="True" --elesys="True" --musys="True" --var="Mjj6"  --tag="SSZ100CRmm" --reg="muon-SS-Z100-CR" --lab="SS ZCR #mu#mu" --samples="HNmumuFit" --icut="6" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_v2_052_SYS" --output="./HN_v052_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"

python ../ssdilep/scripts/merge.py -y "True" --varName="obs_Mjj" --rebinToEq="True" --elesys="True" --musys="True" --var="Mjj6"  --tag="SSZCRmm" --reg="muon-SS-Z-CR" --lab="SS ZCR #mu#mu" --tag="SSZCRmm" --samples="HNmumuFit" --icut="5" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_v2_052_SYS" --output="./HN_v052_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -y "True" --varName="obs_HT"  --rebinToEq="True" --elesys="True" --musys="True" --var="HT2Lep2Jet_8_broad"  --tag="SSZVRmm" --reg="muon-SS-Z-VR" --lab="SS ZVR #mu#mu" --tag="SSZVRmm" --samples="HNmumuFit" --icut="5" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_v2_052_SYS" --output="./HN_v052_SYS_root" --makeplot=False --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -y "True" --varName="obs_HT"  --rebinToEq="True" --elesys="True" --musys="True" --var="HT8s" --tag="SSZSRmm" --reg="muon-SS-Z-SR" --lab="SS ZSR #mu#mu" --tag="SSZSRmm" --samples="HNmumuFit" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_v2_052_SYS" --output="./HN_v052_SYS_root" --makeplot=False --fakest="FakeFactorGeneral" -S True
# python ../ssdilep/scripts/merge.py -y "True" --varName="obs_Mlljj"   --noNorm="True" --rebinToEq="True" --elesys="True" --musys="True" --var="Mlljj8s" --tag="SSZSRmm" --reg="muon-SS-Z-SR" --lab="SS ZSR #mu#mu" --tag="SSZSRmm" --samples="HNmumuFit" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_v2_052_SYS" --output="./HN_v052_SYS_root" --makeplot=False --fakest="FakeFactorGeneral" -S True

