#!bin/bash

# Strings are passed to the scrieta but this is redundant!

#electron variables
# python ../ssdilep/scripts/merge.py --var="el_lead_eta" --reg="ZWindowSS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest=""
# python ../ssdilep/scripts/merge.py --var="el_lead_eta" --reg="ZWindowOS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest=""
# python ../ssdilep/scripts/merge.py --var="NPV" --reg="ZWindowOS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest=""

# python ../ssdilep/scripts/merge.py --var="el_pt_eta_all" --reg="BeyondZAS" --lab="" --samples="chargeflipTruthPowheg"  --tag="PowhegTrueCHF" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="el_pt_eta_chf2" --reg="BeyondZAS" --lab="" --samples="chargeflipTruthPowheg"  --tag="PowhegTrueCHF" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="el_pt_eta_chf4" --reg="BeyondZAS" --lab="" --samples="chargeflipTruthPowheg"  --tag="PowhegTrueCHF" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""

# python ../ssdilep/scripts/merge.py --var="el_pt_eta_all" --reg="ZWindowAS" --lab="" --samples="chargeflipTruth" --tag="SherpaTrueCHF" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="el_pt_eta_chf2" --reg="ZWindowAS" --lab="" --samples="chargeflipTruth" --tag="SherpaTrueCHF" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="el_pt_eta_chf4" --reg="ZWindowAS" --lab="" --samples="chargeflipTruth" --tag="SherpaTrueCHF" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""

# python ../ssdilep/scripts/merge.py --var="el_lead_pt" --reg="ZWindowSS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="same sign"
# python ../ssdilep/scripts/merge.py --var="el_sublead_pt" --reg="ZWindowSS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="same sign"
# python ../ssdilep/scripts/merge.py --var="el_lead_eta_2" --reg="ZWindowSS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="same sign"
# python ../ssdilep/scripts/merge.py --var="el_sublead_eta_2" --reg="ZWindowSS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="same sign"
# python ../ssdilep/scripts/merge.py --var="el_lead_phi_2" --reg="ZWindowSS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="same sign"
# python ../ssdilep/scripts/merge.py --var="el_sublead_phi_2" --reg="ZWindowSS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="same sign"
# python ../ssdilep/scripts/merge.py --var="invMassPeak_2" --reg="ZWindowSS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="same sign"
# python ../ssdilep/scripts/merge.py --var="NPV" --reg="ZWindowSS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="same sign"
# python ../ssdilep/scripts/merge.py --var="ZbosonPt" --reg="ZWindowSS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="same sign"
# python ../ssdilep/scripts/merge.py --var="ZbosonEta" --reg="ZWindowSS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="same sign"

# python ../ssdilep/scripts/merge.py --var="invMassPeak" --reg="ZWindowAS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="any sign"
# python ../ssdilep/scripts/merge.py --var="el_lead_pt" --reg="ZWindowAS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="any sign"
# python ../ssdilep/scripts/merge.py --var="el_sublead_pt" --reg="ZWindowAS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="any sign"
# python ../ssdilep/scripts/merge.py --var="el_lead_eta" --reg="ZWindowAS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="any sign"
# python ../ssdilep/scripts/merge.py --var="el_sublead_eta" --reg="ZWindowAS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="any sign"
# python ../ssdilep/scripts/merge.py --var="el_lead_phi" --reg="ZWindowAS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="any sign"
# python ../ssdilep/scripts/merge.py --var="el_sublead_phi" --reg="ZWindowAS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="any sign"
# python ../ssdilep/scripts/merge.py --var="NPV" --reg="ZWindowAS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="any sign"
# python ../ssdilep/scripts/merge.py --var="ZbosonPt" --reg="ZWindowAS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="any sign"
# python ../ssdilep/scripts/merge.py --var="ZbosonEta" --reg="ZWindowAS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="any sign"

# #MET
# python ../ssdilep/scripts/merge.py --var="met_trk_et" --reg="ZWindowAS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="any sign"
# python ../ssdilep/scripts/merge.py --var="met_clus_et" --reg="ZWindowAS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="any sign"
# python ../ssdilep/scripts/merge.py --var="met_trk_et" --reg="ZWindowSS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="same sign"
# python ../ssdilep/scripts/merge.py --var="met_clus_et" --reg="ZWindowSS" --lab="" --samples="chargeflip"  --tag="Powheg" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=True --fakest="" --lab="same sign"
### truth studies

# python ../ssdilep/scripts/merge.py --var="el_pt_eta_chf2" --reg="ZeeSS130M300CHF1" --lab="" --samples="chargeflipTruthPowheg" --tag="SherpaTrueCHF" --icut="2" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="el_pt_eta_chf4" --reg="ZeeSS130M300CHF2" --lab="" --samples="chargeflipTruthPowheg" --tag="SherpaTrueCHF" --icut="2" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="el_pt_eta_chf2" --reg="ZeeSS300M1200CHF1" --lab="" --samples="chargeflipTruthPowheg" --tag="SherpaTrueCHF" --icut="2" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="el_pt_eta_chf4" --reg="ZeeSS300M1200CHF2" --lab="" --samples="chargeflipTruthPowheg" --tag="SherpaTrueCHF" --icut="2" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="el_pt_eta_chf2" --reg="ZeeSS1200MCHF1" --lab="" --samples="chargeflipTruthPowheg" --tag="SherpaTrueCHF" --icut="2" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="el_pt_eta_chf4" --reg="ZeeSS1200MCHF2" --lab="" --samples="chargeflipTruthPowheg" --tag="SherpaTrueCHF" --icut="2" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""

# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeOS" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="0" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeOSBothPromp" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeOSCHF1" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeOSCHF2" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeOSBrem" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeOSFSR" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeOSFake" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeOSBothNonPromp" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeSS" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="0" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeSSBothPromp" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeSSCHF1" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeSSCHF1SF" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeSSCHF2" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeSSCHF2SF" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeSSBrem" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeSSFSR" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeSSFake" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeSSBothNonPromp" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeBothCHF" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
# python ../ssdilep/scripts/merge.py --var="invMassLong" --reg="ZeeBothCHFSF" --lab="" --samples="chargeflipTruthPowheg"  --tag="CHFTruth1" --icut="1" --input="/afs/f9.ijs.si/home/miham/ZPeak36_35" --output="./ZPeak36" --makeplot=False --fakest=""
