# python ../ssdilep/scripts/merge.py  -M True -E True --var="invMass_5" --xlabel="m(l^{#pm}l^{#pm}) [GeV]" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSReps" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  -M True -E True --var="invMass_mu5" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="three-lepton-optimized-offdiag-SR" --lab="SR1P3Loff" --tag="SR1P3Loff" --samples="dibosonFit" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSReps" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  -M True -E True --var="invMass_mu3" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="three-lepton-optimized-SR"         --lab="SR1P3Lemu" --tag="SR1P3Lemu" --samples="dibosonFit" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSReps" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  -M True -E True --var="invMass_mu3" --xlabel="m(e^{#pm}e^{#pm}) [GeV]"     --reg="three-electron-optimized-SR"       --lab="SR1P3Lee" --tag="SR1P3Lee"   --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSReps" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  -M True -E True --var="invMass_mu3" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR"           --lab="SR1P3Lmm" --tag="SR1P3Lmm"   --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSReps" --makeplot=True --fakest="FakeFactorGeneral"

# python ../ssdilep/scripts/merge.py  -M True -E True --var="invMassSR2ELall" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="two-lepton-optimized-SR"         --lab="SR1P2Lemu" --tag="SR1P2Lemu" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSReps" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  -M True -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]"     --reg="two-electron-optimized-SR"       --lab="SR1P2Lee" --tag="SR1P2Lee"   --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSReps" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  -M True -E True --var="invMassSR2ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-optimized-SR"           --lab="SR1P2Lmm" --tag="SR1P2Lmm"   --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSReps" --makeplot=True --fakest="FakeFactorGeneral"

#ele CR/VR
# python ../ssdilep/scripts/merge.py  -M True -E True --var="invMass_fit"     --xlabel="m(e^{#pm}e^{#mp}) [GeV]" --reg="opposite-sign-CR" --lab="OSCR" --tag="OSCR" --samples="allSamples" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed/" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# python ../ssdilep/scripts/merge.py  -M True -E True --var="invMass_2"       --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="same-sign-CR"     --lab="SSVRee" --tag="SSVRee" --samples="allSamples" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed/" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# python ../ssdilep/scripts/merge.py  -M True -E True --var="invMass_4"       --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="diboson-CR"       --lab="DBCRee" --tag="DBCRee" --samples="allSamples" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed/" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# python ../ssdilep/scripts/merge.py  -M True -E True --var="invMass_4"       --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="threeElectron-VR" --lab="3LVRee" --tag="3LVRee" --samples="allSamples" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_muVetoSR1_006_fixed/" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"

#mix CR/VR
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_2"  --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="same-sign-CR" --tag="SSVRem" --lab="SSVRem" --samples="allSamples_emu" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_emu_v3_001_fixed" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_4"  --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="diboson-CR"   --lab="DBCRem" --tag="DBCRem" --samples="allSamples_emu" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_emu_v3_001_fixed" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_4" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="threeLep-VR"  --lab="3LVRem" --tag="3LVRem" --samples="allSamples_emu" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_emu_v3_001_fixed" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_5" --xlabel="m(l^{#pm}l^{#pm}) [GeV]" --reg="threeLep-VR" --lab="3LVRem2" --tag="3LVRem2" --samples="allSamples_emu" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"

# #muo CR/VR
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="same-sign-CR" --tag="SSVRmm" --lab="SSVRmm" --samples="allSamples_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="diboson-CR" --lab="DBCRmm" --tag="DBCRmm" --samples="allSamples_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu2" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="threeLep-VR" --lab="3LVRmm" --tag="3LVRmm" --samples="allSamples_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"


# #SR1-3
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu5" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="three-lepton-optimized-offdiag-SR" --lab="SR1P3Lem2" --tag="SR1P3Lem2" --samples="allSamples_emu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="three-lepton-optimized-SR"         --lab="SR1P3Lem" --tag="SR1P3Lem" --samples="allSamples_emu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(e^{#pm}e^{#pm}) [GeV]"     --reg="three-electron-optimized-SR"       --lab="SR1P3Lee" --tag="SR1P3Lee"   --samples="allSamples" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR"           --lab="SR1P3Lmm" --tag="SR1P3Lmm"   --samples="allSamples_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"

# #SR1-2
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="two-lepton-optimized-SR"         --lab="SR1P2Lem" --tag="SR1P2Lem" --samples="allSamples_emu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]"     --reg="two-electron-optimized-SR"       --lab="SR1P2Lee" --tag="SR1P2Lee"   --samples="allSamples" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-optimized-SR"           --lab="SR1P2Lmm" --tag="SR1P2Lmm"   --samples="allSamples_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"

# ## signal eigen vectors
# #SR1-3
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu5" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="three-lepton-optimized-offdiag-SR-signal-eeee" --lab="SR1P3Lem2" --tag="SR1P3Lem2" --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu5" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="three-lepton-optimized-offdiag-SR-signal-eeem" --lab="SR1P3Lem2" --tag="SR1P3Lem2" --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu5" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="three-lepton-optimized-offdiag-SR-signal-eemm" --lab="SR1P3Lem2" --tag="SR1P3Lem2" --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu5" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="three-lepton-optimized-offdiag-SR-signal-emem" --lab="SR1P3Lem2" --tag="SR1P3Lem2" --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu5" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="three-lepton-optimized-offdiag-SR-signal-emmm" --lab="SR1P3Lem2" --tag="SR1P3Lem2" --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu5" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="three-lepton-optimized-offdiag-SR-signal-mmmm" --lab="SR1P3Lem2" --tag="SR1P3Lem2" --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"

# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="three-lepton-optimized-SR-signal-eeee"         --lab="SR1P3Lem" --tag="SR1P3Lem" --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="three-lepton-optimized-SR-signal-eeem"         --lab="SR1P3Lem" --tag="SR1P3Lem" --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="three-lepton-optimized-SR-signal-eemm"         --lab="SR1P3Lem" --tag="SR1P3Lem" --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="three-lepton-optimized-SR-signal-emem"         --lab="SR1P3Lem" --tag="SR1P3Lem" --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="three-lepton-optimized-SR-signal-emmm"         --lab="SR1P3Lem" --tag="SR1P3Lem" --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="three-lepton-optimized-SR-signal-mmmm"         --lab="SR1P3Lem" --tag="SR1P3Lem" --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"

# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(e^{#pm}e^{#pm}) [GeV]"     --reg="three-electron-optimized-SR-signal-eeee"       --lab="SR1P3Lee" --tag="SR1P3Lee"   --samples="signalEigenVectors" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(e^{#pm}e^{#pm}) [GeV]"     --reg="three-electron-optimized-SR-signal-eeem"       --lab="SR1P3Lee" --tag="SR1P3Lee"   --samples="signalEigenVectors" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(e^{#pm}e^{#pm}) [GeV]"     --reg="three-electron-optimized-SR-signal-eemm"       --lab="SR1P3Lee" --tag="SR1P3Lee"   --samples="signalEigenVectors" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(e^{#pm}e^{#pm}) [GeV]"     --reg="three-electron-optimized-SR-signal-emem"       --lab="SR1P3Lee" --tag="SR1P3Lee"   --samples="signalEigenVectors" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(e^{#pm}e^{#pm}) [GeV]"     --reg="three-electron-optimized-SR-signal-emmm"       --lab="SR1P3Lee" --tag="SR1P3Lee"   --samples="signalEigenVectors" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(e^{#pm}e^{#pm}) [GeV]"     --reg="three-electron-optimized-SR-signal-mmmm"       --lab="SR1P3Lee" --tag="SR1P3Lee"   --samples="signalEigenVectors" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"

# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR-signal-eeee"           --lab="SR1P3Lmm" --tag="SR1P3Lmm"   --samples="signalEigenVectors" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR-signal-eeem"           --lab="SR1P3Lmm" --tag="SR1P3Lmm"   --samples="signalEigenVectors" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR-signal-eemm"           --lab="SR1P3Lmm" --tag="SR1P3Lmm"   --samples="signalEigenVectors" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR-signal-emem"           --lab="SR1P3Lmm" --tag="SR1P3Lmm"   --samples="signalEigenVectors" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR-signal-emmm"           --lab="SR1P3Lmm" --tag="SR1P3Lmm"   --samples="signalEigenVectors" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMass_mu3" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR-signal-mmmm"           --lab="SR1P3Lmm" --tag="SR1P3Lmm"   --samples="signalEigenVectors" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_001" --output="./AllSR" --makeplot=False --fakest="FakeFactorGeneral"

# #SR1-2
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="two-lepton-optimized-SR-signal-emX"          --lab="SR1P2Lem" --tag="SR1P2Lem" --samples="signalEigenVectors" --icut="9" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="two-lepton-optimized-SR-signal-eeee"         --lab="SR1P2Lem" --tag="SR1P2Lem" --samples="signalEigenVectors" --icut="9" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="two-lepton-optimized-SR-signal-eeem"         --lab="SR1P2Lem" --tag="SR1P2Lem" --samples="signalEigenVectors" --icut="9" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="two-lepton-optimized-SR-signal-eemm"         --lab="SR1P2Lem" --tag="SR1P2Lem" --samples="signalEigenVectors" --icut="9" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="two-lepton-optimized-SR-signal-emem"         --lab="SR1P2Lem" --tag="SR1P2Lem" --samples="signalEigenVectors" --icut="9" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="two-lepton-optimized-SR-signal-emmm"         --lab="SR1P2Lem" --tag="SR1P2Lem" --samples="signalEigenVectors" --icut="9" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="two-lepton-optimized-SR-signal-mmmm"         --lab="SR1P2Lem" --tag="SR1P2Lem" --samples="signalEigenVectors" --icut="9" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"

# python ../ssdilep/scripts/merge.py --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]"      --reg="two-electron-optimized-SR-signal-eeX"        --lab="SR1P2Lee" --tag="SR1P2Lee"   --samples="signalEigenVectors" --icut="9" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]"     --reg="two-electron-optimized-SR-signal-eeee"       --lab="SR1P2Lee" --tag="SR1P2Lee"   --samples="signalEigenVectors" --icut="9" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]"     --reg="two-electron-optimized-SR-signal-eeem"       --lab="SR1P2Lee" --tag="SR1P2Lee"   --samples="signalEigenVectors" --icut="9" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]"     --reg="two-electron-optimized-SR-signal-eemm"       --lab="SR1P2Lee" --tag="SR1P2Lee"   --samples="signalEigenVectors" --icut="9" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]"     --reg="two-electron-optimized-SR-signal-emem"       --lab="SR1P2Lee" --tag="SR1P2Lee"   --samples="signalEigenVectors" --icut="9" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]"     --reg="two-electron-optimized-SR-signal-emmm"       --lab="SR1P2Lee" --tag="SR1P2Lee"   --samples="signalEigenVectors" --icut="9" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]"     --reg="two-electron-optimized-SR-signal-mmmm"       --lab="SR1P2Lee" --tag="SR1P2Lee"   --samples="signalEigenVectors" --icut="9" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"

# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-optimized-SR-signal-mmX"            --lab="SR1P2Lmm" --tag="SR1P2Lmm"   --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-optimized-SR-signal-eeee"           --lab="SR1P2Lmm" --tag="SR1P2Lmm"   --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-optimized-SR-signal-eeem"           --lab="SR1P2Lmm" --tag="SR1P2Lmm"   --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-optimized-SR-signal-eemm"           --lab="SR1P2Lmm" --tag="SR1P2Lmm"   --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-optimized-SR-signal-emem"           --lab="SR1P2Lmm" --tag="SR1P2Lmm"   --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-optimized-SR-signal-emmm"           --lab="SR1P2Lmm" --tag="SR1P2Lmm"   --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py  --rebinToEq="True" --varName="obs_mee" -M True -E True --var="invMassSR2ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-optimized-SR-signal-mmmm"           --lab="SR1P2Lmm" --tag="SR1P2Lmm"   --samples="signalEigenVectors" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./AllSR_2" --makeplot=False --fakest="FakeFactorGeneral"


## SSVR
python ../ssdilep/scripts/merge.py -y False -E True --var="invMass_6" --xlabel="m(l^{#pm}l^{#pm}) [GeV]"     --reg="two-electron-extended-VR" --lab="SSVR" --tag="SSVR" --samples="SSVR" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR1P2L_003/" --output="./SSVRStudy" --makeplot=True --fakest="FakeFactorGeneral"
