#
# 2 lep elec
#

python ../ssdilep/scripts/merge.py -y True -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="two-electron-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="two-electron-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="ZbosonPt_SR_2" --xlabel="p_{T}(e^{#pm}e^{#pm}) [GeV]" --reg="two-electron-optimized-SR" --reg="two-electron-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}e^{#pm})" --reg="two-electron-optimized-SR" --reg="two-electron-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="nleptons" --xlabel="N(l)" --reg="two-electron-optimized-SR" --reg="two-electron-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="nsspairs" --xlabel="N(e^{#pm}e^{#pm})" --reg="two-electron-optimized-SR" --reg="two-electron-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
# python ../ssdilep/scripts/merge.py -y True -E True --var="NPV" --reg="two-electron-optimized-SR" --reg="two-electron-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="met_trk_et" --reg="two-electron-optimized-SR" --reg="two-electron-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead l)" --reg="two-electron-optimized-SR" --reg="two-electron-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead l)" --reg="two-electron-optimized-SR" --reg="two-electron-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="el_lead_eta_2" --xlabel="#eta(lead l)" --reg="two-electron-optimized-SR" --reg="two-electron-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead l)" --reg="two-electron-optimized-SR" --reg="two-electron-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRee 100
# python ../ssdilep/scripts/merge.py -y True -E True --var="el_lead_phi_2" --xlabel="#phi(lead l)" --reg="two-electron-optimized-SR" --reg="two-electron-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
# python ../ssdilep/scripts/merge.py -y True -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead l)" --reg="two-electron-optimized-SR" --reg="two-electron-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100


#
# 2 lep mix
#

python ../ssdilep/scripts/merge.py -y True -M True -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="ZbosonPt_SR_2" --xlabel="p_{T}(e^{#pm}#mu^{#pm}) [GeV]" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}#mu^{#pm})" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="nleptons" --xlabel="N(l)" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="nsspairs" --xlabel="N(e^{#pm}#mu^{#pm})" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -y True -M True -E True --var="NPV" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="met_trk_et" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead l)" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead l)" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="el_lead_eta_2" --xlabel="#eta(lead l)" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead l)" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRem 100
# python ../ssdilep/scripts/merge.py -y True -M True -E True --var="el_lead_phi_2" --xlabel="#phi(lead l)" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -y True -M True -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead l)" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_emu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100

#
# 2 lep muon
#


python ../ssdilep/scripts/merge.py -y True -M True --var="invMassSR2ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="DR2" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="ZbosonPt_SR_2" --xlabel="p_{T}(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="ZbosonEta_2" --xlabel="#eta(#mu^{#pm}#mu^{#pm})" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="nleptons" --xlabel="N(#mu)" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="nsspairs" --xlabel="N(#mu^{#pm}#mu^{#pm})" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -y True -M True --var="NPV" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="met_trk_et" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="el_lead_pt_2" --xlabel="p_{T}(lead #mu)" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead #mu)" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="el_lead_eta_2" --xlabel="#eta(lead #mu)" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="el_sublead_eta_2" --xlabel="#eta(sublead #mu)" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRmm 100
# python ../ssdilep/scripts/merge.py -y True -M True --var="el_lead_phi_2" --xlabel="#phi(lead #mu)" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -y True -M True --var="el_sublead_phi_2" --xlabel="#phi(sublead #mu)" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100


#
# 3 lep ele
#
python ../ssdilep/scripts/merge.py -y True -E True --var="invMass_mu3" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="HT" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="invMassOS1" --xlabel="lead m(e^{#pm}e^{#pm}) [GeV]" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="invMassOS2" --xlabel="sublead m(e^{#pm}e^{#pm}) [GeV]" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="ZbosonPt_SR" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRee 100
# python ../ssdilep/scripts/merge.py -y True -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}e^{#pm})" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="nleptons" --xlabel="N(e)" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="nsspairs" --xlabel="N(e^{#pm}e^{#pm})" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
# python ../ssdilep/scripts/merge.py -y True -E True --var="njets" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
# python ../ssdilep/scripts/merge.py -y True -E True --var="nbjets" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
# python ../ssdilep/scripts/merge.py -y True -E True --var="NPV" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="met_trk_et" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
# python ../ssdilep/scripts/merge.py -y True -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead e)" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead e)" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="el_third_pt_SR" --xlabel="p_{T}(third e)" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="el_lead_eta_2" --xlabel="#eta(lead e)" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead e)" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
python ../ssdilep/scripts/merge.py -y True -E True --var="el_third_eta_2" --xlabel="#eta(third e)" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
# python ../ssdilep/scripts/merge.py -y True -E True --var="el_lead_phi_2" --xlabel="#phi(lead e)" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
# python ../ssdilep/scripts/merge.py -y True -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead e)" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100
# python ../ssdilep/scripts/merge.py -y True -E True --var="el_third_phi_2" --xlabel="#phi(third e)" --reg="three-electron-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRee 100


#
# 3 lep muon
#
python ../ssdilep/scripts/merge.py -y True -M True --var="invMass_mu3" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="DR2" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="HT" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="invMassOS1" --xlabel="lead m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="invMassOS2" --xlabel="sublead m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="ZbosonPt_SR" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRmm 100
# python ../ssdilep/scripts/merge.py -y True -M True --var="ZbosonEta_2" --xlabel="#eta(#mu^{#pm}#mu^{#pm})" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="nleptons" --xlabel="N(#mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="nsspairs" --xlabel="N(#mu^{#pm}#mu^{#pm})" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -y True -M True --var="njets" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -y True -M True --var="nbjets" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -y True -M True --var="NPV" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="met_trk_et" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -y True -M True --var="el_lead_pt_2" --xlabel="p_{T}(lead #mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead #mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="el_third_pt_SR" --xlabel="p_{T}(third #mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="el_lead_eta_2" --xlabel="#eta(lead #mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="el_sublead_eta_2" --xlabel="#eta(sublead #mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
python ../ssdilep/scripts/merge.py -y True -M True --var="el_third_eta_2" --xlabel="#eta(third #mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -y True -M True --var="el_lead_phi_2" --xlabel="#phi(lead #mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -y True -M True --var="el_sublead_phi_2" --xlabel="#phi(sublead #mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -y True -M True --var="el_third_phi_2" --xlabel="#phi(third #mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRmm 100


#
# 3 lep mix
#
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="invMass_mu5" --xlabel="m(l^{#pm}l^{#pm}) [GeV]" --reg="three-lepton-optimized-offdiag-SR" --lab="optimized SR 1P3L (l^{#pm}l^{#pm}l'^{#mp})" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="invMass_mu3" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="HT" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="invMassOS1" --xlabel="lead m(e^{#pm}#mu^{#pm}) [GeV]" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="invMassOS2" --xlabel="sublead m(e^{#pm}#mu^{#pm}) [GeV]" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="ZbosonPt_SR" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True  --BRem 100
# python ../ssdilep/scripts/merge.py -y True -M True -E True --var="ZbosonEta_2" --xlabel="#eta(e^{#pm}#mu^{#pm})" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="nleptons" --xlabel="N(l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="nsspairs" --xlabel="N(e^{#pm}#mu^{#pm})" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -y True -M True -E True --var="njets" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -y True -M True -E True --var="nbjets" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -y True -M True -E True --var="NPV" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="met_trk_et" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="el_lead_pt_2" --xlabel="p_{T}(lead l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="el_third_pt_SR" --xlabel="p_{T}(third l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="el_lead_eta_2" --xlabel="#eta(lead l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="el_sublead_eta_2" --xlabel="#eta(sublead l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -y True -M True -E True --var="el_third_eta_2" --xlabel="#eta(third l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -y True -M True -E True --var="el_lead_phi_2" --xlabel="#phi(lead l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -y True -M True -E True --var="el_sublead_phi_2" --xlabel="#phi(sublead l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -y True -M True -E True --var="el_third_phi_2" --xlabel="#phi(third l)" --reg="three-lepton-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="8" --input="/ceph/grid/home/atlas/miham/AnalysisCode/All_SR_002_flashback/" --output="./All_SR_002_flashback" --makeplot=True --fakest="FakeFactorGeneral"  --signal=True --BRem 100