# # #!bin/bash

# ##SSVR
# python ../ssdilep/scripts/merge.py -M True --var="invMass_mu" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="DR2" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="DR4" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_2" --xlabel="p_{T}(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="ZbosonEta_2" --xlabel="#eta(#mu^{#pm}#mu^{#pm})" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="nleptons" --xlabel="N(#mu)" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="nsspairs" --xlabel="N(#mu^{#pm}#mu^{#pm})" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="NPV" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="met_trk_et" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_pt_2" --xlabel="p_{T}(lead #mu)" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead #mu)" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_eta_2" --xlabel="#eta(lead #mu)" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_eta_2" --xlabel="#eta(sublead #mu)" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_phi_2" --xlabel="#phi(lead #mu)" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_phi_2" --xlabel="#phi(sublead #mu)" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# # ##diboson
# python ../ssdilep/scripts/merge.py -M True --var="invMass_mu" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="HT2" --xlabel="#Sigma p_{T} [GeV]" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="DR4" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="DR4" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="invMassOS1" --xlabel="lead m(#mu^{#pm}#mu^{#pm}) [GeV]"  --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="invMassOS2" --xlabel="sublead m(#mu^{#pm}#mu^{#pm}) [GeV]"  --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_2" --xlabel="p_{T}(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="ZbosonEta_2" --xlabel="#eta(#mu^{#pm}#mu^{#pm})" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="nleptons" --xlabel="N(#mu)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="njets" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="nbjets" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="NPV" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="met_trk_et" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_pt_2" --xlabel="p_{T}(lead #mu)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead #mu)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_third_pt_2" --xlabel="p_{T}(third #mu)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_eta_2" --xlabel="#eta(lead #mu)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_eta_2" --xlabel="#eta(sublead #mu)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_third_eta_2" --xlabel="#eta(third #mu)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_phi_2" --xlabel="#phi(lead #mu)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_phi_2" --xlabel="#phi(sublead #mu)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_third_phi_2" --xlabel="#phi(third #mu)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# # # ##three electron
# python ../ssdilep/scripts/merge.py -M True --var="invMass_mu2" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -M True --var="HT2" --xlabel="#Sigma p_{T} [GeV]" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="DR4" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="DR4" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="invMassOS1" --xlabel="lead m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="invMassOS2" --xlabel="sublead m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_2" --xlabel="p_{T}(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="ZbosonEta_2" --xlabel="#eta(#mu^{#pm}#mu^{#pm})" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="nleptons" --xlabel="N(#mu)" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -M True --var="njets" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -M True --var="nbjets" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -M True --var="NPV" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="met_trk_et" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_pt_2" --xlabel="p_{T}(lead #mu)" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead #mu)" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_third_pt_2" --xlabel="p_{T}(third #mu)" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_eta_2" --xlabel="#eta(lead #mu)" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_eta_2" --xlabel="#eta(sublead #mu)" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_third_eta_2" --xlabel="#eta(third #mu)" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_phi_2" --xlabel="#phi(lead #mu)" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_phi_2" --xlabel="#phi(sublead #mu)" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True --var="el_third_phi_2" --xlabel="#phi(third #mu)" --reg="threeLep-VR" --lab="3LVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral"
# # ## two + three ele SR
# python ../ssdilep/scripts/merge.py -M True --var="invMassSR2ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="DR2" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_SR_2" --xlabel="p_{T}(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="ZbosonEta_2" --xlabel="#eta(#mu^{#pm}#mu^{#pm})" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="nleptons" --xlabel="N(#mu)" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="nsspairs" --xlabel="N(#mu^{#pm}#mu^{#pm})" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="NPV" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="met_trk_et" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_lead_pt_2" --xlabel="p_{T}(lead #mu)" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead #mu)" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_lead_eta_2" --xlabel="#eta(lead #mu)" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_sublead_eta_2" --xlabel="#eta(sublead #mu)" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_lead_phi_2" --xlabel="#phi(lead #mu)" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_sublead_phi_2" --xlabel="#phi(sublead #mu)" --reg="SR-muon-SR" --reg="SR-muon-SR" --lab="SR#mu#mu" --tag="SR1" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # # ## two ele SR
# python ../ssdilep/scripts/merge.py -M True --var="invMassSR2ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="DR2" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="two-muon-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="two-muon-dR-SR" --lab="SR 1P2L (dR cut only)" --tag="SR1-2" --samples="SSVR_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_SR_2" --xlabel="p_{T}(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_SR_2" --xlabel="p_{T}(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-dR-SR" --lab="SR 1P2L (dR cut only)" --tag="SR1-2" --samples="SSVR_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="ZbosonEta_2" --xlabel="#eta(#mu^{#pm}#mu^{#pm})" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="nleptons" --xlabel="N(#mu)" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="NPV" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="met_trk_et" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_lead_pt_2" --xlabel="p_{T}(lead #mu)" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead #mu)" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_lead_eta_2" --xlabel="#eta(lead #mu)" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_sublead_eta_2" --xlabel="#eta(sublead #mu)" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_lead_phi_2" --xlabel="#phi(lead #mu)" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_sublead_phi_2" --xlabel="#phi(sublead #mu)" --reg="two-muon-SR" --reg="two-muon-SR" --lab="SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # # # ## optimized two ele SR
# python ../ssdilep/scripts/merge.py -M True --var="invMassSR2ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="invMassSR2EL" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=False --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="DR2" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_SR_2" --xlabel="p_{T}(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="ZbosonEta_2" --xlabel="#eta(#mu^{#pm}#mu^{#pm})" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="nleptons" --xlabel="N(#mu)" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="nsspairs" --xlabel="N(#mu^{#pm}#mu^{#pm})" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="NPV" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="met_trk_et" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_lead_pt_2" --xlabel="p_{T}(lead #mu)" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead #mu)" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_lead_eta_2" --xlabel="#eta(lead #mu)" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_sublead_eta_2" --xlabel="#eta(sublead #mu)" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_lead_phi_2" --xlabel="#phi(lead #mu)" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_sublead_phi_2" --xlabel="#phi(sublead #mu)" --reg="two-muon-optimized-SR" --reg="two-muon-optimized-SR" --lab="optimized SR 1P2L" --tag="SR1-2" --samples="SSVR_mu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # # # ## three ele SR
# python ../ssdilep/scripts/merge.py -M True --var="invMassSR3ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="invMassSR3EL" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="DR2" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="three-muon-dR-SR" --lab="SR 1P3L (dR cut only)" --tag="SR1-3" --samples="dibosonFit_mu" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_SR" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_SR" --reg="three-muon-dR-SR" --lab="SR 1P3L (dR cut only)" --tag="SR1-3" --samples="dibosonFit_mu" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="invMassOS1" --xlabel="lead m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="invMassOS2" --xlabel="sublead m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="ZbosonEta_2" --xlabel="#eta(#mu^{#pm}#mu^{#pm})" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="nleptons" --xlabel="N(#mu)" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="nsspairs" --xlabel="N(#mu^{#pm}#mu^{#pm})" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="njets" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="nbjets" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="NPV" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="met_trk_et" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_lead_pt_2" --xlabel="p_{T}(lead #mu)" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead #mu)" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_third_pt_SR" --xlabel="p_{T}(third #mu)" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_lead_eta_2" --xlabel="#eta(lead #mu)" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_sublead_eta_2" --xlabel="#eta(sublead #mu)" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_third_eta_2" --xlabel="#eta(third #mu)" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_lead_phi_2" --xlabel="#phi(lead #mu)" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_sublead_phi_2" --xlabel="#phi(sublead #mu)" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_third_phi_2" --xlabel="#phi(third #mu)" --reg="three-muon-SR" --lab="SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # # # ## optimized three ele SR
# python ../ssdilep/scripts/merge.py -M True --var="invMassSR3ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="invMassSR3EL" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="DR2" --xlabel="#DeltaR(#mu^{#pm}#mu^{#pm})" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="HT" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="invMassOS1" --xlabel="lead m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="invMassOS2" --xlabel="sublead m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="ZbosonPt_SR" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="ZbosonEta_2" --xlabel="#eta(#mu^{#pm}#mu^{#pm})" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="nleptons" --xlabel="N(#mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="nsspairs" --xlabel="N(#mu^{#pm}#mu^{#pm})" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="njets" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="nbjets" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="NPV" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="met_trk_et" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# # python ../ssdilep/scripts/merge.py -M True --var="el_lead_pt_2" --xlabel="p_{T}(lead #mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_pt_2" --xlabel="p_{T}(sublead #mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="el_third_pt_SR" --xlabel="p_{T}(third #mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_eta_2" --xlabel="#eta(lead #mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_eta_2" --xlabel="#eta(sublead #mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="el_third_eta_2" --xlabel="#eta(third #mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="el_lead_phi_2" --xlabel="#phi(lead #mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="el_sublead_phi_2" --xlabel="#phi(sublead #mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100
# python ../ssdilep/scripts/merge.py -M True --var="el_third_phi_2" --xlabel="#phi(third #mu)" --reg="three-muon-optimized-SR" --lab="optimized SR 1P3L" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_mu_v3_007" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRmm 100


# python ../ssdilep/scripts/merge.py -M True --var="invMass_fit" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="opposite-sign-bveto-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# python ../ssdilep/scripts/merge.py -M True --var="invMass_2" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="same-sign-CR" --tag="SSVR" --lab="SSVR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# python ../ssdilep/scripts/merge.py -M True --var="invMass_fit" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="OSTTCR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# python ../ssdilep/scripts/merge.py -M True --var="invMass_3" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="SSTTVR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# python ../ssdilep/scripts/merge.py -M True --var="invMass_4" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="diboson-CR" --lab="DBCR" --tag="DBCR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# python ../ssdilep/scripts/merge.py -M True --var="invMass_4" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="threeLep-VR" --lab="3LVR" --tag="DBCRZveto" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"

# python ../ssdilep/scripts/merge.py -M True --var="invMassSR2ELall" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="SR-muon-SR" --lab="SR1" --tag="SR1" --samples="allSamples" --icut="8" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal=True --rebinToEq="True" --varName="obs_mee"


# # python ../ssdilep/scripts/merge.py -M True --var="invMassSR3EL" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-optimized-SR" --lab="SR 1P3L" --tag="3ELSR" --samples="allSamples" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal=True --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py -M True --var="invMassSR2EL" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-optimized-SR" --lab="SR 1P2L" --tag="2ELSR" --samples="allSamples" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal=True --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py -M True --var="invMassSR2EL" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="two-muon-SR" --tag="2ELSR" --samples="SSVR_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal="True" --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py -M True --var="invMassSR3EL" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-SR" --lab="SR 1P3L" --tag="3ELSR" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal="True" --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py -M True --var="el_third_pt_SR" --xlabel="p_{T}(third #mu)" --xlabel="m(#mu^{#pm}#mu^{#pm}) [GeV]" --reg="three-muon-SR" --lab="SR 1P3L" --tag="3ELSR" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_mu_v3_007" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal="True" --rebinToEq="True" --varName="obs_pt"

