# python ../ssdilep/scripts/merge.py --var="invMassSR2ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_017merged/" --output="./SR" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="invMassSR2EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_017merged/" --output="./SR" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="DR2" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_017merged/" --output="./SR" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_017merged/" --output="./SR" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="two-ele-dR-SR" --lab="SR1-2 (dR cut only)" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_017merged/" --output="./SR" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="ZbosonPt_SR_2" --reg="two-ele-SR" --reg="two-ele-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_017merged/" --output="./SR" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="ZbosonPt_SR_2" --reg="two-ele-dR-SR" --lab="SR1-2 (dR cut only)" --tag="SR1-2" --samples="SSVR" --icut="5" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_017merged/" --output="./SR" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="invMassSR2EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="two-ele-optimized-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_017merged/" --output="./SR" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=False



# python ../ssdilep/scripts/merge.py --var="invMassSR3ELall" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_017merged/" --output="./SR" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="invMassSR3EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_017merged/" --output="./SR" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True
# python ../ssdilep/scripts/merge.py --var="DR2" --xlabel="#DeltaR(e^{#pm}e^{#pm})" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_017merged/" --output="./SR" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_017merged/" --output="./SR" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="three-ele-dR-SR" --lab="SR1-3 (dR cut only)" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_017merged/" --output="./SR" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="ZbosonPt_SR" --reg="three-ele-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="4" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_017merged/" --output="./SR" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
# python ../ssdilep/scripts/merge.py --var="ZbosonPt_SR" --reg="three-ele-dR-SR" --lab="SR1-3 (dR cut only)" --tag="SR1-3" --samples="dibosonFit" --icut="5" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_017merged/" --output="./SR" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True
python ../ssdilep/scripts/merge.py --var="invMassSR3EL" --xlabel="m(e^{#pm}e^{#pm}) [GeV]" --reg="three-ele-optimized-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/AllR_v3_017merged/" --output="./SR" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True