# # # #!bin/bash

# # ##SSVR
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMass_3" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="DR4" --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonEta_2" --xlabel="eta(Z)" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="nleptons" --xlabel="N(l)" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="nsspairs" --xlabel="N(e^{#pm}#mu^{#pm})" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="NPV" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="met_trk_et" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_pt_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_pt_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_eta_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_eta_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_phi_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_phi_2" --reg="same-sign-CR" --tag="SSVR" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# # # ##diboson
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMass_DB" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="DR4" --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassOS1" --xlabel="lead m(e^{#pm}#mu^{#mp}) [GeV]"  --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassOS2" --xlabel="sublead m(e^{#pm}#mu^{#mp}) [GeV]"  --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonEta_2" --xlabel="eta(Z)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="nleptons" --xlabel="N(l)" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="njets" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="nbjets" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="NPV" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="met_trk_et" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_pt_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_pt_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_pt_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_eta_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_eta_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_eta_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_phi_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_phi_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_phi_2" --reg="diboson-CR" --lab="DBCR" --tag="diboson" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# # # # ##three electron
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMass_4" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="DR4" --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassOS1" --xlabel="lead m(e^{#pm}#mu^{#mp}) [GeV]" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassOS2" --xlabel="sublead m(e^{#pm}#mu^{#mp}) [GeV]" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonEta_2" --xlabel="eta(Z)" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="nleptons" --xlabel="N(l)" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -M True -E True --var="njets" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -M True -E True --var="nbjets" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# # python ../ssdilep/scripts/merge.py -M True -E True --var="NPV" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="met_trk_et" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_pt_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_pt_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_pt_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_eta_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_eta_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_eta_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_phi_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_phi_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_phi_2" --reg="threeLep-VR" --lab="DBVR" --tag="threeLepVR" --samples="diboson" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral"
# # # ## two + three ele SR
python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_SR_2" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonEta_2" --xlabel="eta(Z)" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="nleptons" --xlabel="N(l)" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="nsspairs" --xlabel="N(e^{#pm}#mu^{#pm})" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="NPV" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="met_trk_et" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_pt_2" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_pt_2" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_eta_2" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_eta_2" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_phi_2" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_phi_2" --reg="SR-lepton-SR" --reg="SR-lepton-SR" --lab="SRe#mu" --tag="SR1" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # ## two ele SR
python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="two-lepton-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="two-lepton-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="two-lepton-SR" --reg="two-lepton-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="two-lepton-dR-SR" --lab="SR1-2 (dR cut only)" --tag="SR1-2" --samples="SSVR_emu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_SR_2" --reg="two-lepton-SR" --reg="two-lepton-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_SR_2" --reg="two-lepton-dR-SR" --lab="SR1-2 (dR cut only)" --tag="SR1-2" --samples="SSVR_emu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonEta_2" --xlabel="eta(Z)" --reg="two-lepton-SR" --reg="two-lepton-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="nleptons" --xlabel="N(l)" --reg="two-lepton-SR" --reg="two-lepton-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="NPV" --reg="two-lepton-SR" --reg="two-lepton-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="met_trk_et" --reg="two-lepton-SR" --reg="two-lepton-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_pt_2" --reg="two-lepton-SR" --reg="two-lepton-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_pt_2" --reg="two-lepton-SR" --reg="two-lepton-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_eta_2" --reg="two-lepton-SR" --reg="two-lepton-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_eta_2" --reg="two-lepton-SR" --reg="two-lepton-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_phi_2" --reg="two-lepton-SR" --reg="two-lepton-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_phi_2" --reg="two-lepton-SR" --reg="two-lepton-SR" --lab="SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="3" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # # ## optimized two ele SR
python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="two-lepton-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR2EL" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="two-lepton-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=False--BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="two-lepton-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_SR_2" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonEta_2" --xlabel="eta(Z)" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="nleptons" --xlabel="N(l)" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="nsspairs" --xlabel="N(e^{#pm}#mu^{#pm})" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="NPV" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="met_trk_et" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_pt_2" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_pt_2" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_eta_2" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_eta_2" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_phi_2" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_phi_2" --reg="two-lepton-optimized-SR" --reg="two-lepton-optimized-SR" --lab="optimized SR1-2" --tag="SR1-2" --samples="SSVR_emu" --icut="6" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # # ## three ele SR
python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR3ELall" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR3EL" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="HT" --xlabel="#Sigma p_{T} [GeV]" --reg="three-lepton-dR-SR" --lab="SR1-3 (dR cut only)" --tag="SR1-3" --samples="dibosonFit_mu" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_SR" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_SR" --reg="three-lepton-dR-SR" --lab="SR1-3 (dR cut only)" --tag="SR1-3" --samples="dibosonFit_mu" --icut="5" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassOS1" --xlabel="lead m(e^{#pm}#mu^{#mp}) [GeV]" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassOS2" --xlabel="sublead m(e^{#pm}#mu^{#mp}) [GeV]" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonEta_2" --xlabel="eta(Z)" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="nleptons" --xlabel="N(l)" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="nsspairs" --xlabel="N(e^{#pm}#mu^{#pm})" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="njets" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="nbjets" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="NPV" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="met_trk_et" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_pt_2" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_pt_2" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_pt_SR" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_eta_2" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_eta_2" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_eta_2" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_phi_2" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_phi_2" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_phi_2" --reg="three-lepton-SR" --lab="SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# # # ## optimized three ele SR
python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR3ELall" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR3EL" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="DR2" --xlabel="#DeltaR(e^{#pm}#mu^{#pm})" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="HT" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassOS1" --xlabel="lead m(e^{#pm}#mu^{#mp}) [GeV]" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="invMassOS2" --xlabel="sublead m(e^{#pm}#mu^{#mp}) [GeV]" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonPt_SR" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --logy=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="ZbosonEta_2" --xlabel="eta(Z)" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="nleptons" --xlabel="N(l)" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="nsspairs" --xlabel="N(e^{#pm}#mu^{#pm})" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="njets" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="nbjets" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="NPV" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
python ../ssdilep/scripts/merge.py -M True -E True --var="met_trk_et" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_pt_2" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_pt_2" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_pt_SR" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_eta_2" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_eta_2" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_eta_2" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_lead_phi_2" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_sublead_phi_2" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100
# python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_phi_2" --reg="three-lepton-optimized-SR" --lab="optimized SR1-3" --tag="SR1-3" --samples="dibosonFit_mu" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_emu_v3_001" --makeplot=True --fakest="FakeFactorGeneral" --blind=-9999 --signal=True --BRem 100


# # python ../ssdilep/scripts/merge.py -M True -E True --var="invMass_fit" --xlabel="m(e^{#pm}#mu^{#mp}) [GeV]" --reg="opposite-sign-bveto-CR" --lab="OSCR" --samples="OSCR" --tag="OSCR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py -M True -E True --var="invMass_2" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="same-sign-CR" --tag="SSVR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py -M True -E True --var="invMass_fit" --xlabel="m(e^{#pm}#mu^{#mp}) [GeV]" --reg="opposite-sign-ttbar-CR" --lab="TTCR (OSCR + 1/2 b-jet)" --tag="OSTTCR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py -M True -E True --var="invMass_3" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="same-sign-ttbar-CR" --lab="TTVR (SSVR + 1/2 b-jet)" --tag="SSTTVR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py -M True -E True --var="invMass_4" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="diboson-CR" --lab="DBCR" --tag="DBCR" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"
# # python ../ssdilep/scripts/merge.py -M True -E True --var="invMass_4" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="threeLep-VR" --lab="DBVR" --tag="DBCRZveto" --samples="allSamples" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --rebinToEq="True" --varName="obs_mee"

# # python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR2ELall" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="SR-lepton-SR" --lab="SR1" --tag="SR1" --samples="allSamples" --icut="8" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal=True --rebinToEq="True" --varName="obs_mee"


# # # python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR3EL" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="three-lepton-optimized-SR" --lab="SR1-3" --tag="3ELSR" --samples="allSamples" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal=True --rebinToEq="True" --varName="obs_mee"
# # # python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR2EL" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="two-lepton-optimized-SR" --lab="SR1-2" --tag="2ELSR" --samples="allSamples" --icut="7" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001/" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal=True --rebinToEq="True" --varName="obs_mee"
# # # python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR2EL" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="two-lepton-SR" --tag="2ELSR" --samples="SSVR_emu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal="True" --rebinToEq="True" --varName="obs_mee"
# # # python ../ssdilep/scripts/merge.py -M True -E True --var="invMassSR3EL" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="three-lepton-SR" --lab="SR1-3" --tag="3ELSR" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal="True" --rebinToEq="True" --varName="obs_mee"
# # # python ../ssdilep/scripts/merge.py -M True -E True --var="el_third_pt_SR" --xlabel="m(e^{#pm}#mu^{#pm}) [GeV]" --reg="three-lepton-SR" --lab="SR1-3" --tag="3ELSR" --samples="dibosonFit_mu" --icut="4" --input="/afs/f9.ijs.si/home/miham/AllR_emu_v3_001" --output="./AllR_v3_muVetoSR1_005_root" --makeplot=False --fakest="FakeFactorGeneral" --signal="True" --rebinToEq="True" --varName="obs_pt"

