#!bin/bash

# Strings are passed to the scrieta but this is redundant!


python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="met_trk_et_WJets" --reg="Wjets-VR" --lab="" --tag="WJets" --icut="0" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="el_eta" --reg="Wjets-VR" --lab="" --tag="WJets" --icut="0" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="el_phi" --reg="Wjets-VR" --lab="" --tag="WJets" --icut="0" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --logy="False" --samples="wjet" --var="el_pt" --reg="Wjets-VR" --lab="" --tag="WJets" --icut="0" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="met_trk_mt" --reg="Wjets-VR" --lab="" --tag="WJets" --icut="0" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="njets" --reg="Wjets-VR" --lab="" --tag="WJets" --icut="0" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"

python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="met_trk_et_WJets" --reg="Wjets-TwoJets-VR" --lab="at least two jets" --tag="WJets" --icut="1" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="el_eta" --reg="Wjets-TwoJets-VR" --lab="at least two jets" --tag="WJets" --icut="1" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="el_phi" --reg="Wjets-TwoJets-VR" --lab="at least two jets" --tag="WJets" --icut="1" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --logy="False" --samples="wjet" --var="el_pt" --reg="Wjets-TwoJets-VR" --lab="at least two jets" --tag="WJets" --icut="1" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="met_trk_mt" --reg="Wjets-TwoJets-VR" --lab="at least two jets" --tag="WJets" --icut="1" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="njets" --reg="Wjets-TwoJets-VR" --lab="at least two jets" --tag="WJets" --icut="1" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"


python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="met_trk_et_WJets_tight" --reg="Wjets-tight-VR" --lab="MET < 60, MT < 120" --tag="WJets" --icut="2" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="el_eta" --reg="Wjets-tight-VR" --lab="MET < 60, MT < 120" --tag="WJets" --icut="2" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="el_phi" --reg="Wjets-tight-VR" --lab="MET < 60, MT < 120" --tag="WJets" --icut="2" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --logy="False" --samples="wjet" --var="el_pt" --reg="Wjets-tight-VR" --lab="MET < 60, MT < 120" --tag="WJets" --icut="2" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="el_pt" --reg="Wjets-tight-VR" --lab="MET < 60, MT < 120" --tag="WJets" --icut="2" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="met_trk_mt_tight" --reg="Wjets-tight-VR" --lab="MET < 60, MT < 120" --tag="WJets" --icut="2" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --ymin 10 --samples="wjet" --var="njets" --reg="Wjets-tight-VR" --lab="MET < 60, MT < 120" --tag="WJets" --icut="2" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"


python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="met_trk_et_WJets_tight" --reg="Wjets-tight-TwoJets-VR" --lab="MET < 60, MT < 120, 2 jets" --tag="WJets" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="el_eta" --reg="Wjets-tight-TwoJets-VR" --lab="MET < 60, MT < 120, 2 jets" --tag="WJets" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="el_phi" --reg="Wjets-tight-TwoJets-VR" --lab="MET < 60, MT < 120, 2 jets" --tag="WJets" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="el_pt" --reg="Wjets-tight-TwoJets-VR" --lab="MET < 60, MT < 120, 2 jets" --tag="WJets" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="met_trk_mt_tight" --reg="Wjets-tight-TwoJets-VR" --lab="MET < 60, MT < 120, 2 jets" --tag="WJets" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -E True --samples="wjet" --var="njets" --reg="Wjets-tight-TwoJets-VR" --lab="MET < 60, MT < 120, 2 jets" --tag="WJets" --icut="3" --input="/ceph/grid/home/atlas/miham/AnalysisCode/WJets_HN_010/" --output="./WJets_HN_010" --makeplot=True --fakest="FakeFactorGeneral"
