# # #!bin/bash

# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="nelectrons" --xlabel="N(e)" --reg="electron-OS-Z-CR" --lab="OS ZCR ee" --tag="OSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="Mjj" --xlabel="m(jj) [GeV]" --reg="electron-OS-Z-CR" --lab="OS ZCR ee" --tag="OSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="invMassZCR" --xlabel="m(ee) [GeV]" --reg="electron-OS-Z-CR" --lab="OS ZCR ee" --tag="OSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="el_lead_pt" --reg="electron-OS-Z-CR" --lab="OS ZCR ee" --tag="OSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="el_sublead_pt" --reg="electron-OS-Z-CR" --lab="OS ZCR ee" --tag="OSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="el_lead_eta" --reg="electron-OS-Z-CR" --lab="OS ZCR ee" --tag="OSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="el_sublead_eta" --reg="electron-OS-Z-CR" --lab="OS ZCR ee" --tag="OSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="el_sublead_pt" --reg="electron-OS-Z-CR" --lab="OS ZCR ee" --tag="OSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="njets" --xlabel="m(ee) [GeV]" --reg="electron-OS-Z-CR" --lab="OS ZCR ee" --tag="OSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"

# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="nelectrons" --xlabel="N(e)" --reg="electron-SS-Z-CR" --lab="SS ZCR ee" --tag="SSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="Mjj2" --xlabel="m(jj) [GeV]" --reg="electron-SS-Z-CR" --lab="SS ZCR ee" --tag="SSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="invMassZCR" --xlabel="m(ll) [GeV]" --reg="electron-SS-Z-CR" --lab="SS ZCR ee" --tag="SSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="el_lead_pt" --reg="electron-SS-Z-CR" --lab="SS ZCR ee" --tag="SSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="njets" --reg="electron-SS-Z-CR" --lab="SS ZCR ee" --tag="SSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"

# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="nelectrons" --xlabel="N(e)" --reg="electron-OS-Z-VR" --lab="OS ZVR ee" --tag="OSZVRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="Mjj" --xlabel="m(jj) [GeV]" --reg="electron-OS-Z-VR" --lab="OS ZVR ee" --tag="OSZVRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="invMassZVR1" --xlabel="m(ee) [GeV]" --reg="electron-OS-Z-VR" --lab="OS ZVR ee" --tag="OSZVRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="el_lead_pt" --reg="electron-OS-Z-VR" --lab="OS ZVR ee" --tag="OSZVRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="njets" --reg="electron-OS-Z-VR" --lab="OS ZVR ee" --tag="OSZVRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"

# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="nelectrons" --xlabel="N(e)" --reg="electron-SS-Z-VR" --lab="SS ZVR ee" --tag="SSZVRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="Mjj2" --xlabel="m(jj) [GeV]" --reg="electron-SS-Z-VR" --lab="SS ZVR ee" --tag="SSZVRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="invMassZVR2" --xlabel="m(ee) [GeV]" --reg="electron-SS-Z-VR" --lab="SS ZVR ee" --tag="SSZVRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="el_lead_pt" --reg="electron-SS-Z-VR" --lab="SS ZVR ee" --tag="SSZVRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y True --elesys="True" --var="njets" --reg="electron-SS-Z-VR" --lab="SS ZVR ee" --tag="SSZVRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"

python ../ssdilep/scripts/merge.py -S True -y True --elesys="True" --var="nelectrons" --xlabel="N(e)" --reg="electron-OS-Z-SR" --lab="OS ZSR ee" --tag="OSZSRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -S True -y True --elesys="True" --var="Mjj" --xlabel="m(jj) [GeV]" --reg="electron-OS-Z-SR" --lab="OS ZSR ee" --tag="OSZSRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -S True -y True --elesys="True" --var="invMassZSR1" --xlabel="m(ee) [GeV]" --reg="electron-OS-Z-SR" --lab="OS ZSR ee" --tag="OSZSRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -S True -y True --elesys="True" --var="el_lead_pt" --reg="electron-OS-Z-SR" --lab="OS ZSR ee" --tag="OSZSRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -S True -y True --elesys="True" --var="njets" --reg="electron-OS-Z-SR" --lab="OS ZSR ee" --tag="OSZSRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"

python ../ssdilep/scripts/merge.py -S True -y True --elesys="True" --var="nelectrons" --xlabel="N(e)" --reg="electron-SS-Z-SR" --lab="SS ZSR ee" --tag="SSZSRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -S True -y True --elesys="True" --var="Mjj2" --xlabel="m(jj) [GeV]" --reg="electron-SS-Z-SR" --lab="SS ZSR ee" --tag="SSZSRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -S True -y True --elesys="True" --var="invMassZSR2" --xlabel="m(ee) [GeV]" --reg="electron-SS-Z-SR" --lab="SS ZSR ee" --tag="SSZSRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -S True -y True --elesys="True" --var="el_lead_pt" --reg="electron-SS-Z-SR" --lab="SS ZSR ee" --tag="SSZSRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
python ../ssdilep/scripts/merge.py -S True -y True --elesys="True" --var="njets" --reg="electron-SS-Z-SR" --lab="SS ZSR ee" --tag="SSZSRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"



# python ../ssdilep/scripts/merge.py -y False --var="nelectrons" --xlabel="N(#mu)" --reg="muon-OS-Z-CR" --lab="OS ZCR #mu#mu" --tag="OSZCRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y False --var="Mjj" --xlabel="m(jj) [GeV]"   --reg="muon-OS-Z-CR" --lab="OS ZCR #mu#mu" --tag="OSZCRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y False --var="invMassZCR" --xlabel="m(#mu#mu) [GeV]"   --reg="muon-OS-Z-CR" --lab="OS ZCR #mu#mu" --tag="OSZCRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"

# python ../ssdilep/scripts/merge.py -y False --var="nelectrons" --xlabel="N(#mu)" --reg="muon-SS-Z-CR" --lab="SS ZCR #mu#mu" --tag="SSZCRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y False --var="Mjj3" --xlabel="m(jj) [GeV]"   --reg="muon-SS-Z-CR" --lab="SS ZCR #mu#mu" --tag="SSZCRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y False --var="invMassZCR3" --xlabel="m(#mu#mu) [GeV]"   --reg="muon-SS-Z-CR" --lab="SS ZCR #mu#mu" --tag="SSZCRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"

# python ../ssdilep/scripts/merge.py -y False --var="nelectrons" --xlabel="N(#mu)" --reg="muon-OS-Z-VR" --lab="OS ZVR #mu#mu" --tag="OSZVRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y False --var="Mjj" --xlabel="m(jj) [GeV]"   --reg="muon-OS-Z-VR" --lab="OS ZVR #mu#mu" --tag="OSZVRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y False --var="invMassZVR1" --xlabel="m(#mu#mu) [GeV]"   --reg="muon-OS-Z-VR" --lab="OS ZVR #mu#mu" --tag="OSZVRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"

# python ../ssdilep/scripts/merge.py -y False --var="nelectrons" --xlabel="N(#mu)" --reg="muon-SS-Z-VR" --lab="SS ZVR #mu#mu" --tag="SSZVRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y False --var="Mjj3" --xlabel="m(jj) [GeV]"   --reg="muon-SS-Z-VR" --lab="SS ZVR #mu#mu" --tag="SSZVRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"
# python ../ssdilep/scripts/merge.py -y False --var="invMassZVR3" --xlabel="m(#mu#mu) [GeV]"   --reg="muon-SS-Z-VR" --lab="SS ZVR #mu#mu" --tag="SSZVRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN" --makeplot=True --fakest="FakeFactorGeneral"







# python ../ssdilep/scripts/merge.py -y False --var="nelectrons" --xlabel="N(e)" --reg="electron-OS-Z-CR" --lab="OS ZCR ee" --tag="OSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"
# python ../ssdilep/scripts/merge.py -y False --var="Mjj" --xlabel="m(jj) [GeV]" --reg="electron-OS-Z-CR" --lab="OS ZCR ee" --tag="OSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"
# python ../ssdilep/scripts/merge.py -y False --var="invMassZCR" --xlabel="m(ee) [GeV]" --reg="electron-OS-Z-CR" --lab="OS ZCR ee" --tag="OSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"

# python ../ssdilep/scripts/merge.py -y False --var="nelectrons" --xlabel="N(e)" --reg="electron-SS-Z-CR" --lab="SS ZCR ee" --tag="SSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"
# python ../ssdilep/scripts/merge.py -y False --var="Mjj2" --xlabel="m(jj) [GeV]" --reg="electron-SS-Z-CR" --lab="SS ZCR ee" --tag="SSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"
# python ../ssdilep/scripts/merge.py -y False --var="invMassZCR" --xlabel="m(ll) [GeV]" --reg="electron-SS-Z-CR" --lab="SS ZCR ee" --tag="SSZCRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"

# python ../ssdilep/scripts/merge.py -y False --var="nelectrons" --xlabel="N(e)" --reg="electron-OS-Z-VR" --lab="OS ZVR ee" --tag="OSZVRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"
# python ../ssdilep/scripts/merge.py -y False --var="Mjj" --xlabel="m(jj) [GeV]" --reg="electron-OS-Z-VR" --lab="OS ZVR ee" --tag="OSZVRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"
# python ../ssdilep/scripts/merge.py -y False --var="invMassZVR1" --xlabel="m(ee) [GeV]" --reg="electron-OS-Z-VR" --lab="OS ZVR ee" --tag="OSZVRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"

# python ../ssdilep/scripts/merge.py -y False --var="nelectrons" --xlabel="N(e)" --reg="electron-SS-Z-VR" --lab="SS ZVR ee" --tag="SSZVRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"
# python ../ssdilep/scripts/merge.py -y False --var="Mjj2" --xlabel="m(jj) [GeV]" --reg="electron-SS-Z-VR" --lab="SS ZVR ee" --tag="SSZVRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"
# python ../ssdilep/scripts/merge.py -y False --var="invMassZVR2" --xlabel="m(ee) [GeV]" --reg="electron-SS-Z-VR" --lab="SS ZVR ee" --tag="SSZVRee" --samples="HNee" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"



# python ../ssdilep/scripts/merge.py -y False --var="nelectrons" --xlabel="N(#mu)" --reg="muon-OS-Z-CR" --lab="OS ZCR #mu#mu" --tag="OSZCRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"
# python ../ssdilep/scripts/merge.py -y False --var="Mjj" --xlabel="m(jj) [GeV]"   --reg="muon-OS-Z-CR" --lab="OS ZCR #mu#mu" --tag="OSZCRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"
# python ../ssdilep/scripts/merge.py -y False --var="invMassZCR" --xlabel="m(#mu#mu) [GeV]"   --reg="muon-OS-Z-CR" --lab="OS ZCR #mu#mu" --tag="OSZCRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"

# python ../ssdilep/scripts/merge.py -y False --var="nelectrons" --xlabel="N(#mu)" --reg="muon-SS-Z-CR" --lab="SS ZCR #mu#mu" --tag="SSZCRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"
# python ../ssdilep/scripts/merge.py -y False --var="Mjj3" --xlabel="m(jj) [GeV]"   --reg="muon-SS-Z-CR" --lab="SS ZCR #mu#mu" --tag="SSZCRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"
# python ../ssdilep/scripts/merge.py -y False --var="invMassZCR3" --xlabel="m(#mu#mu) [GeV]"   --reg="muon-SS-Z-CR" --lab="SS ZCR #mu#mu" --tag="SSZCRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"

# python ../ssdilep/scripts/merge.py -y False --var="nelectrons" --xlabel="N(#mu)" --reg="muon-OS-Z-VR" --lab="OS ZVR #mu#mu" --tag="OSZVRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"
# python ../ssdilep/scripts/merge.py -y False --var="Mjj" --xlabel="m(jj) [GeV]"   --reg="muon-OS-Z-VR" --lab="OS ZVR #mu#mu" --tag="OSZVRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"
# python ../ssdilep/scripts/merge.py -y False --var="invMassZVR1" --xlabel="m(#mu#mu) [GeV]"   --reg="muon-OS-Z-VR" --lab="OS ZVR #mu#mu" --tag="OSZVRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"

# python ../ssdilep/scripts/merge.py -y False --var="nelectrons" --xlabel="N(#mu)" --reg="muon-SS-Z-VR" --lab="SS ZVR #mu#mu" --tag="SSZVRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"
# python ../ssdilep/scripts/merge.py -y False --var="Mjj3" --xlabel="m(jj) [GeV]"   --reg="muon-SS-Z-VR" --lab="SS ZVR #mu#mu" --tag="SSZVRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"
# python ../ssdilep/scripts/merge.py -y False --var="invMassZVR3" --xlabel="m(#mu#mu) [GeV]"   --reg="muon-SS-Z-VR" --lab="SS ZVR #mu#mu" --tag="SSZVRmm" --samples="HNmumu" --icut="7" --input="/ceph/grid/home/atlas/miham/AnalysisCode/HN_010" --output="./HN_MCFakes" --makeplot=True --fakest="MCFakes"
